# generated by fastapi-codegen:
#   filename:  swagger.yml
#   timestamp: 2026-04-30T12:03:51+00:00

from __future__ import annotations

from datetime import datetime
from typing import List, Optional, Union

from fastapi import FastAPI, Header, HTTPException, Path, Query, Request
from fastapi.routing import APIRoute
from pydantic import conint, constr

from .models import (
    ACL,
    AbortPresignMultipartUpload,
    ActionRun,
    ActionRunList,
    AuthCapabilities,
    AuthenticationToken,
    BranchCreation,
    BranchProtectionRule,
    CherryPickCreation,
    Commit,
    CommitCreation,
    CommitList,
    CommitRecordCreation,
    CommPrefsInput,
    CompletePresignMultipartUpload,
    Config,
    Credentials,
    CredentialsList,
    CredentialsWithSecret,
    CurrentUser,
    DiffList,
    Error,
    ErrorNoACL,
    ExternalLoginInformation,
    ExternalPrincipal,
    ExternalPrincipalCreation,
    ExternalPrincipalList,
    FindMergeBaseResult,
    GarbageCollectionConfig,
    GarbageCollectionPrepareResponse,
    GarbageCollectionRules,
    Group,
    GroupCreation,
    GroupList,
    HookRunList,
    ImportCreation,
    ImportCreationResponse,
    ImportStatus,
    InstallationUsageReport,
    LoginInformation,
    Merge,
    MergeResult,
    ObjectCopyCreation,
    ObjectErrorList,
    ObjectStageCreation,
    ObjectStats,
    ObjectStatsList,
    PathList,
    Policy,
    PolicyList,
    PrepareGarbageCollectionCommitsStatus,
    PrepareGCUncommittedRequest,
    PrepareGCUncommittedResponse,
    PresignMultipartUpload,
    PullRequest,
    PullRequestBasic,
    PullRequestCreation,
    PullRequestCreationResponse,
    PullRequestsList,
    Ref,
    RefList,
    RefsDump,
    RefsRestore,
    RepositoriesRepositoryBranchProtectionDeleteRequest,
    Repository,
    RepositoryCreation,
    RepositoryDumpStatus,
    RepositoryList,
    RepositoryMetadata,
    RepositoryMetadataKeys,
    RepositoryMetadataSet,
    RepositoryRestoreStatus,
    ResetCreation,
    RevertCreation,
    Setup,
    SetupState,
    StagingLocation,
    StagingMetadata,
    StatsEventsList,
    Status4,
    StorageConfig,
    StorageURI,
    StsAuthRequest,
    TagCreation,
    TaskCreation,
    TaskInfo,
    Type4,
    Type6,
    UnderlyingObjectProperties,
    UpdateObjectUserMetadata,
    UploadPartCopyFrom,
    UploadPartFrom,
    UploadTo,
    User,
    UserCreation,
    UserList,
    VersionConfig,
)

app = FastAPI(
    description='lakeFS HTTP API',
    title='lakeFS API',
    license={
        'name': 'Apache 2.0',
        'url': 'https://www.apache.org/licenses/LICENSE-2.0.html',
    },
    version='1.0.0',
    servers=[{'url': '/api/v1', 'description': 'lakeFS server endpoint'}],
)

app.router.prefix = '/api/v1'



@app.get('/healthcheck', response_model=None, tags=['healthCheck'])
def health_check() -> None:
    pass