# generated by fastapi-codegen:
#   filename:  swagger.yml
#   timestamp: 2026-04-30T12:03:51+00:00

from __future__ import annotations

from datetime import datetime
from typing import List, Optional, Union

from fastapi import FastAPI, Header, Path, Query, Request, UploadFile
from pydantic import conint, constr

from .models import (
    ACL,
    AbortPresignMultipartUpload,
    ActionRun,
    ActionRunList,
    AuthCapabilities,
    AuthenticationToken,
    BranchCreation,
    BranchProtectionRule,
    CherryPickCreation,
    Commit,
    CommitCreation,
    CommitList,
    CommitRecordCreation,
    CommPrefsInput,
    CompletePresignMultipartUpload,
    Config,
    Credentials,
    CredentialsList,
    CredentialsWithSecret,
    CurrentUser,
    DiffList,
    Error,
    ErrorNoACL,
    ExternalLoginInformation,
    ExternalPrincipal,
    ExternalPrincipalCreation,
    ExternalPrincipalList,
    FindMergeBaseResult,
    GarbageCollectionConfig,
    GarbageCollectionPrepareResponse,
    GarbageCollectionRules,
    Group,
    GroupCreation,
    GroupList,
    HookRunList,
    ImportCreation,
    ImportCreationResponse,
    ImportStatus,
    InstallationUsageReport,
    LoginInformation,
    Merge,
    MergeResult,
    ObjectCopyCreation,
    ObjectErrorList,
    ObjectStageCreation,
    ObjectStats,
    ObjectStatsList,
    PathList,
    Policy,
    PolicyList,
    PrepareGarbageCollectionCommitsStatus,
    PrepareGCUncommittedRequest,
    PrepareGCUncommittedResponse,
    PresignMultipartUpload,
    PullRequest,
    PullRequestBasic,
    PullRequestCreation,
    PullRequestCreationResponse,
    PullRequestsList,
    Ref,
    RefList,
    RefsDump,
    RefsRestore,
    RepositoriesRepositoryBranchProtectionDeleteRequest,
    Repository,
    RepositoryCreation,
    RepositoryDumpStatus,
    RepositoryList,
    RepositoryMetadata,
    RepositoryMetadataKeys,
    RepositoryMetadataSet,
    RepositoryRestoreStatus,
    ResetCreation,
    RevertCreation,
    Setup,
    SetupState,
    StagingLocation,
    StagingMetadata,
    StatsEventsList,
    Status4,
    StorageConfig,
    StorageURI,
    StsAuthRequest,
    TagCreation,
    TaskCreation,
    TaskInfo,
    Type4,
    Type6,
    UnderlyingObjectProperties,
    UpdateObjectUserMetadata,
    UploadPartCopyFrom,
    UploadPartFrom,
    UploadTo,
    User,
    UserCreation,
    UserList,
    VersionConfig,
)

app = FastAPI(
    description='lakeFS HTTP API',
    title='lakeFS API',
    license={
        'name': 'Apache 2.0',
        'url': 'https://www.apache.org/licenses/LICENSE-2.0.html',
    },
    version='1.0.0',
    servers=[{'url': '/api/v1', 'description': 'lakeFS server endpoint'}],
)


@app.get(
    '/auth/capabilities',
    response_model=AuthCapabilities,
    responses={'default': {'model': Error}},
    tags=['internal'],
)
def get_auth_capabilities() -> Union[AuthCapabilities, Error]:
    """
    list authentication capabilities supported
    """
    pass


@app.post(
    '/auth/external/principal/login',
    response_model=AuthenticationToken,
    responses={
        '400': {'model': Error},
        '401': {'model': Error},
        '403': {'model': Error},
        '404': {'model': Error},
        'default': {'model': Error},
    },
    tags=['external', 'experimental', 'auth'],
)
def external_principal_login(
    body: ExternalLoginInformation = None,
) -> Union[AuthenticationToken, Error]:
    """
    perform a login using an external authenticator
    """
    pass


@app.get(
    '/auth/external/principals',
    response_model=ExternalPrincipal,
    responses={
        '400': {'model': Error},
        '401': {'model': Error},
        '404': {'model': Error},
        'default': {'model': Error},
    },
    tags=['auth', 'external', 'experimental'],
)
def get_external_principal(
    principal_id: str = Query(..., alias='principalId')
) -> Union[ExternalPrincipal, Error]:
    """
    describe external principal by id
    """
    pass


@app.get(
    '/auth/groups',
    response_model=GroupList,
    responses={
        '400': {'model': Error},
        '401': {'model': Error},
        'default': {'model': Error},
    },
    tags=['auth'],
)
def list_groups(
    prefix: Optional[str] = None,
    after: Optional[str] = None,
    amount: Optional[conint(ge=-1, le=1000)] = 100,
) -> Union[GroupList, Error]:
    """
    list groups
    """
    pass


@app.post(
    '/auth/groups',
    response_model=None,
    responses={
        '201': {'model': Group},
        '400': {'model': Error},
        '401': {'model': Error},
        '404': {'model': Error},
        'default': {'model': Error},
    },
    tags=['auth'],
)
def create_group(body: GroupCreation = None) -> Union[None, Group, Error]:
    """
    create group
    """
    pass


@app.get(
    '/auth/groups/{groupId}',
    response_model=Group,
    responses={
        '400': {'model': Error},
        '401': {'model': Error},
        '404': {'model': Error},
        'default': {'model': Error},
    },
    tags=['auth'],
)
def get_group(group_id: str = Path(..., alias='groupId')) -> Union[Group, Error]:
    """
    get group
    """
    pass


@app.delete(
    '/auth/groups/{groupId}',
    response_model=None,
    responses={
        '400': {'model': Error},
        '401': {'model': Error},
        '404': {'model': Error},
        'default': {'model': Error},
    },
    tags=['auth'],
)
def delete_group(group_id: str = Path(..., alias='groupId')) -> Union[None, Error]:
    """
    delete group
    """
    pass


@app.post(
    '/auth/groups/{groupId}/acl',
    response_model=None,
    responses={
        '400': {'model': Error},
        '401': {'model': Error},
        '404': {'model': Error},
        'default': {'model': Error},
    },
    tags=['auth'],
)
def set_group_a_c_l(
    group_id: str = Path(..., alias='groupId'), body: ACL = ...
) -> Union[None, Error]:
    """
    set ACL of group
    """
    pass


@app.get(
    '/auth/groups/{groupId}/acl',
    response_model=ACL,
    responses={
        '400': {'model': Error},
        '401': {'model': Error},
        '404': {'model': ErrorNoACL},
        'default': {'model': Error},
    },
    tags=['auth'],
)
def get_group_a_c_l(
    group_id: str = Path(..., alias='groupId')
) -> Union[ACL, Error, ErrorNoACL]:
    """
    get ACL of group
    """
    pass


@app.get(
    '/auth/groups/{groupId}/members',
    response_model=UserList,
    responses={
        '400': {'model': Error},
        '401': {'model': Error},
        'default': {'model': Error},
    },
    tags=['auth'],
)
def list_group_members(
    prefix: Optional[str] = None,
    after: Optional[str] = None,
    amount: Optional[conint(ge=-1, le=1000)] = 100,
    group_id: str = Path(..., alias='groupId'),
) -> Union[UserList, Error]:
    """
    list group members
    """
    pass


@app.put(
    '/auth/groups/{groupId}/members/{userId}',
    response_model=None,
    responses={
        '400': {'model': Error},
        '401': {'model': Error},
        '404': {'model': Error},
        'default': {'model': Error},
    },
    tags=['auth'],
)
def add_group_membership(
    group_id: str = Path(..., alias='groupId'), user_id: str = Path(..., alias='userId')
) -> Union[None, Error]:
    """
    add group membership
    """
    pass


@app.delete(
    '/auth/groups/{groupId}/members/{userId}',
    response_model=None,
    responses={
        '400': {'model': Error},
        '401': {'model': Error},
        '404': {'model': Error},
        'default': {'model': Error},
    },
    tags=['auth'],
)
def delete_group_membership(
    group_id: str = Path(..., alias='groupId'), user_id: str = Path(..., alias='userId')
) -> Union[None, Error]:
    """
    delete group membership
    """
    pass


@app.get(
    '/auth/groups/{groupId}/policies',
    response_model=PolicyList,
    responses={
        '400': {'model': Error},
        '401': {'model': Error},
        '404': {'model': Error},
        'default': {'model': Error},
    },
    tags=['auth'],
)
def list_group_policies(
    prefix: Optional[str] = None,
    after: Optional[str] = None,
    amount: Optional[conint(ge=-1, le=1000)] = 100,
    group_id: str = Path(..., alias='groupId'),
) -> Union[PolicyList, Error]:
    """
    list group policies
    """
    pass


@app.put(
    '/auth/groups/{groupId}/policies/{policyId}',
    response_model=None,
    responses={
        '400': {'model': Error},
        '401': {'model': Error},
        '404': {'model': Error},
        'default': {'model': Error},
    },
    tags=['auth'],
)
def attach_policy_to_group(
    group_id: str = Path(..., alias='groupId'),
    policy_id: str = Path(..., alias='policyId'),
) -> Union[None, Error]:
    """
    attach policy to group
    """
    pass


@app.delete(
    '/auth/groups/{groupId}/policies/{policyId}',
    response_model=None,
    responses={
        '400': {'model': Error},
        '401': {'model': Error},
        '404': {'model': Error},
        'default': {'model': Error},
    },
    tags=['auth'],
)
def detach_policy_from_group(
    group_id: str = Path(..., alias='groupId'),
    policy_id: str = Path(..., alias='policyId'),
) -> Union[None, Error]:
    """
    detach policy from group
    """
    pass


@app.post(
    '/auth/login',
    response_model=AuthenticationToken,
    responses={
        '400': {'model': Error},
        '401': {'model': Error},
        'default': {'model': Error},
    },
    tags=['auth'],
)
def login(body: LoginInformation = None) -> Union[AuthenticationToken, Error]:
    """
    perform a login
    """
    pass


@app.get(
    '/auth/policies',
    response_model=PolicyList,
    responses={
        '400': {'model': Error},
        '401': {'model': Error},
        'default': {'model': Error},
    },
    tags=['auth'],
)
def list_policies(
    prefix: Optional[str] = None,
    after: Optional[str] = None,
    amount: Optional[conint(ge=-1, le=1000)] = 100,
) -> Union[PolicyList, Error]:
    """
    list policies
    """
    pass


@app.post(
    '/auth/policies',
    response_model=None,
    responses={
        '201': {'model': Policy},
        '400': {'model': Error},
        '401': {'model': Error},
        '409': {'model': Error},
        'default': {'model': Error},
    },
    tags=['auth'],
)
def create_policy(body: Policy) -> Union[None, Policy, Error]:
    """
    create policy
    """
    pass


@app.get(
    '/auth/policies/{policyId}',
    response_model=Policy,
    responses={
        '400': {'model': Error},
        '401': {'model': Error},
        '404': {'model': Error},
        'default': {'model': Error},
    },
    tags=['auth'],
)
def get_policy(policy_id: str = Path(..., alias='policyId')) -> Union[Policy, Error]:
    """
    get policy
    """
    pass


@app.put(
    '/auth/policies/{policyId}',
    response_model=Policy,
    responses={
        '400': {'model': Error},
        '401': {'model': Error},
        '404': {'model': Error},
        'default': {'model': Error},
    },
    tags=['auth'],
)
def update_policy(
    policy_id: str = Path(..., alias='policyId'), body: Policy = ...
) -> Union[Policy, Error]:
    """
    update policy
    """
    pass


@app.delete(
    '/auth/policies/{policyId}',
    response_model=None,
    responses={
        '400': {'model': Error},
        '401': {'model': Error},
        '404': {'model': Error},
        'default': {'model': Error},
    },
    tags=['auth'],
)
def delete_policy(policy_id: str = Path(..., alias='policyId')) -> Union[None, Error]:
    """
    delete policy
    """
    pass


@app.get(
    '/auth/users',
    response_model=UserList,
    responses={
        '400': {'model': Error},
        '401': {'model': Error},
        'default': {'model': Error},
    },
    tags=['auth'],
)
def list_users(
    prefix: Optional[str] = None,
    after: Optional[str] = None,
    amount: Optional[conint(ge=-1, le=1000)] = 100,
) -> Union[UserList, Error]:
    """
    list users
    """
    pass


@app.post(
    '/auth/users',
    response_model=None,
    responses={
        '201': {'model': User},
        '400': {'model': Error},
        '401': {'model': Error},
        '409': {'model': Error},
        'default': {'model': Error},
    },
    tags=['auth'],
)
def create_user(body: UserCreation = None) -> Union[None, User, Error]:
    """
    create user
    """
    pass


@app.get(
    '/auth/users/{userId}',
    response_model=User,
    responses={
        '400': {'model': Error},
        '401': {'model': Error},
        '404': {'model': Error},
        'default': {'model': Error},
    },
    tags=['auth'],
)
def get_user(user_id: str = Path(..., alias='userId')) -> Union[User, Error]:
    """
    get user
    """
    pass


@app.delete(
    '/auth/users/{userId}',
    response_model=None,
    responses={
        '400': {'model': Error},
        '401': {'model': Error},
        '404': {'model': Error},
        'default': {'model': Error},
    },
    tags=['auth'],
)
def delete_user(user_id: str = Path(..., alias='userId')) -> Union[None, Error]:
    """
    delete user
    """
    pass


@app.get(
    '/auth/users/{userId}/credentials',
    response_model=CredentialsList,
    responses={
        '400': {'model': Error},
        '401': {'model': Error},
        '404': {'model': Error},
        'default': {'model': Error},
    },
    tags=['auth'],
)
def list_user_credentials(
    prefix: Optional[str] = None,
    after: Optional[str] = None,
    amount: Optional[conint(ge=-1, le=1000)] = 100,
    user_id: str = Path(..., alias='userId'),
) -> Union[CredentialsList, Error]:
    """
    list user credentials
    """
    pass


@app.post(
    '/auth/users/{userId}/credentials',
    response_model=None,
    responses={
        '201': {'model': CredentialsWithSecret},
        '400': {'model': Error},
        '401': {'model': Error},
        '404': {'model': Error},
        'default': {'model': Error},
    },
    tags=['auth'],
)
def create_credentials(
    user_id: str = Path(..., alias='userId')
) -> Union[None, CredentialsWithSecret, Error]:
    """
    create credentials
    """
    pass


@app.delete(
    '/auth/users/{userId}/credentials/{accessKeyId}',
    response_model=None,
    responses={
        '400': {'model': Error},
        '401': {'model': Error},
        '404': {'model': Error},
        'default': {'model': Error},
    },
    tags=['auth'],
)
def delete_credentials(
    user_id: str = Path(..., alias='userId'),
    access_key_id: str = Path(..., alias='accessKeyId'),
) -> Union[None, Error]:
    """
    delete credentials
    """
    pass


@app.get(
    '/auth/users/{userId}/credentials/{accessKeyId}',
    response_model=Credentials,
    responses={
        '400': {'model': Error},
        '401': {'model': Error},
        '404': {'model': Error},
        'default': {'model': Error},
    },
    tags=['auth'],
)
def get_credentials(
    user_id: str = Path(..., alias='userId'),
    access_key_id: str = Path(..., alias='accessKeyId'),
) -> Union[Credentials, Error]:
    """
    get credentials
    """
    pass


@app.post(
    '/auth/users/{userId}/external/principals',
    response_model=None,
    responses={
        '400': {'model': Error},
        '401': {'model': Error},
        '404': {'model': Error},
        '409': {'model': Error},
        'default': {'model': Error},
    },
    tags=['auth', 'external', 'experimental'],
)
def create_user_external_principal(
    user_id: str = Path(..., alias='userId'),
    principal_id: str = Query(..., alias='principalId'),
    body: ExternalPrincipalCreation = None,
) -> Union[None, Error]:
    """
    attach external principal to user
    """
    pass


@app.delete(
    '/auth/users/{userId}/external/principals',
    response_model=None,
    responses={
        '400': {'model': Error},
        '401': {'model': Error},
        '404': {'model': Error},
        'default': {'model': Error},
    },
    tags=['auth', 'external', 'experimental'],
)
def delete_user_external_principal(
    user_id: str = Path(..., alias='userId'),
    principal_id: str = Query(..., alias='principalId'),
) -> Union[None, Error]:
    """
    delete external principal from user
    """
    pass


@app.get(
    '/auth/users/{userId}/external/principals/ls',
    response_model=ExternalPrincipalList,
    responses={
        '400': {'model': Error},
        '401': {'model': Error},
        '404': {'model': Error},
        'default': {'model': Error},
    },
    tags=['auth', 'external', 'experimental'],
)
def list_user_external_principals(
    prefix: Optional[str] = None,
    after: Optional[str] = None,
    amount: Optional[conint(ge=-1, le=1000)] = 100,
    user_id: str = Path(..., alias='userId'),
) -> Union[ExternalPrincipalList, Error]:
    """
    list user external policies attached to a user
    """
    pass


@app.get(
    '/auth/users/{userId}/groups',
    response_model=GroupList,
    responses={
        '400': {'model': Error},
        '401': {'model': Error},
        '404': {'model': Error},
        'default': {'model': Error},
    },
    tags=['auth'],
)
def list_user_groups(
    prefix: Optional[str] = None,
    after: Optional[str] = None,
    amount: Optional[conint(ge=-1, le=1000)] = 100,
    user_id: str = Path(..., alias='userId'),
) -> Union[GroupList, Error]:
    """
    list user groups
    """
    pass


@app.get(
    '/auth/users/{userId}/policies',
    response_model=PolicyList,
    responses={
        '400': {'model': Error},
        '401': {'model': Error},
        '404': {'model': Error},
        'default': {'model': Error},
    },
    tags=['auth'],
)
def list_user_policies(
    prefix: Optional[str] = None,
    after: Optional[str] = None,
    amount: Optional[conint(ge=-1, le=1000)] = 100,
    effective: Optional[bool] = False,
    user_id: str = Path(..., alias='userId'),
) -> Union[PolicyList, Error]:
    """
    list user policies
    """
    pass


@app.put(
    '/auth/users/{userId}/policies/{policyId}',
    response_model=None,
    responses={
        '400': {'model': Error},
        '401': {'model': Error},
        '404': {'model': Error},
        'default': {'model': Error},
    },
    tags=['auth'],
)
def attach_policy_to_user(
    user_id: str = Path(..., alias='userId'),
    policy_id: str = Path(..., alias='policyId'),
) -> Union[None, Error]:
    """
    attach policy to user
    """
    pass


@app.delete(
    '/auth/users/{userId}/policies/{policyId}',
    response_model=None,
    responses={
        '400': {'model': Error},
        '401': {'model': Error},
        '404': {'model': Error},
        'default': {'model': Error},
    },
    tags=['auth'],
)
def detach_policy_from_user(
    user_id: str = Path(..., alias='userId'),
    policy_id: str = Path(..., alias='policyId'),
) -> Union[None, Error]:
    """
    detach policy from user
    """
    pass


@app.get(
    '/config',
    response_model=Config,
    responses={'401': {'model': Error}},
    tags=['config'],
)
def get_config() -> Union[Config, Error]:
    pass


@app.get(
    '/config/garbage-collection',
    response_model=GarbageCollectionConfig,
    responses={'401': {'model': Error}},
    tags=['internal'],
)
def get_garbage_collection_config() -> Union[GarbageCollectionConfig, Error]:
    pass


@app.get(
    '/config/storage',
    response_model=StorageConfig,
    responses={'401': {'model': Error}},
    tags=['internal'],
)
def get_storage_config() -> Union[StorageConfig, Error]:
    pass


@app.get(
    '/config/version',
    response_model=VersionConfig,
    responses={'401': {'model': Error}},
    tags=['internal'],
)
def get_lake_f_s_version() -> Union[VersionConfig, Error]:
    pass


@app.get('/healthcheck', response_model=None, tags=['healthCheck'])
def health_check() -> None:
    pass


@app.get(
    '/oidc/callback',
    response_model=None,
    responses={'default': {'model': Error}},
    tags=['auth'],
)
def oauth_callback() -> Union[None, Error]:
    pass


@app.get(
    '/repositories',
    response_model=RepositoryList,
    responses={
        '400': {'model': Error},
        '401': {'model': Error},
        'default': {'model': Error},
    },
    tags=['repositories'],
)
def list_repositories(
    prefix: Optional[str] = None,
    after: Optional[str] = None,
    amount: Optional[conint(ge=-1, le=1000)] = 100,
    search: Optional[str] = None,
) -> Union[RepositoryList, Error]:
    """
    list repositories
    """
    pass


@app.post(
    '/repositories',
    response_model=None,
    responses={
        '201': {'model': Repository},
        '400': {'model': Error},
        '401': {'model': Error},
        '409': {'model': Error},
        'default': {'model': Error},
    },
    tags=['repositories'],
)
def create_repository(
    bare: Optional[bool] = False, body: RepositoryCreation = ...
) -> Union[None, Repository, Error]:
    """
    create repository
    """
    pass


@app.get(
    '/repositories/{repository}',
    response_model=Repository,
    responses={
        '400': {'model': Error},
        '401': {'model': Error},
        '404': {'model': Error},
        'default': {'model': Error},
    },
    tags=['repositories'],
)
def get_repository(repository: str) -> Union[Repository, Error]:
    """
    get repository
    """
    pass


@app.delete(
    '/repositories/{repository}',
    response_model=None,
    responses={
        '400': {'model': Error},
        '401': {'model': Error},
        '404': {'model': Error},
        'default': {'model': Error},
    },
    tags=['repositories'],
)
def delete_repository(
    force: Optional[bool] = False, repository: str = ...
) -> Union[None, Error]:
    """
    delete repository
    """
    pass


@app.get(
    '/repositories/{repository}/actions/runs',
    response_model=ActionRunList,
    responses={
        '400': {'model': Error},
        '401': {'model': Error},
        '404': {'model': Error},
        'default': {'model': Error},
    },
    tags=['actions'],
)
def list_repository_runs(
    repository: str,
    after: Optional[str] = None,
    amount: Optional[conint(ge=-1, le=1000)] = 100,
    branch: Optional[str] = None,
    commit: Optional[str] = None,
) -> Union[ActionRunList, Error]:
    """
    list runs
    """
    pass


@app.get(
    '/repositories/{repository}/actions/runs/{run_id}',
    response_model=ActionRun,
    responses={
        '400': {'model': Error},
        '401': {'model': Error},
        '404': {'model': Error},
        'default': {'model': Error},
    },
    tags=['actions'],
)
def get_run(repository: str, run_id: str = ...) -> Union[ActionRun, Error]:
    """
    get a run
    """
    pass


@app.get(
    '/repositories/{repository}/actions/runs/{run_id}/hooks',
    response_model=HookRunList,
    responses={
        '400': {'model': Error},
        '401': {'model': Error},
        '404': {'model': Error},
        'default': {'model': Error},
    },
    tags=['actions'],
)
def list_run_hooks(
    repository: str,
    run_id: str = ...,
    after: Optional[str] = None,
    amount: Optional[conint(ge=-1, le=1000)] = 100,
) -> Union[HookRunList, Error]:
    """
    list run hooks
    """
    pass


@app.get(
    '/repositories/{repository}/actions/runs/{run_id}/hooks/{hook_run_id}/output',
    response_model=bytes,
    responses={
        '400': {'model': Error},
        '401': {'model': Error},
        '404': {'model': Error},
        'default': {'model': Error},
    },
    tags=['actions'],
)
def get_run_hook_output(
    repository: str, run_id: str = ..., hook_run_id: str = ...
) -> Union[bytes, Error]:
    """
    get run hook output
    """
    pass


@app.get(
    '/repositories/{repository}/branch_protection',
    response_model=List[BranchProtectionRule],
    responses={
        '400': {'model': Error},
        '401': {'model': Error},
        '404': {'model': Error},
        'default': {'model': Error},
    },
    tags=['internal'],
)
def internal_get_branch_protection_rules(
    repository: str,
) -> Union[List[BranchProtectionRule], Error]:
    """
    get branch protection rules
    """
    pass


@app.post(
    '/repositories/{repository}/branch_protection',
    response_model=None,
    responses={
        '400': {'model': Error},
        '401': {'model': Error},
        '404': {'model': Error},
        'default': {'model': Error},
    },
    tags=['internal'],
)
def internal_create_branch_protection_rule(
    repository: str, body: BranchProtectionRule = ...
) -> Union[None, Error]:
    pass


@app.delete(
    '/repositories/{repository}/branch_protection',
    response_model=None,
    responses={
        '400': {'model': Error},
        '401': {'model': Error},
        '404': {'model': Error},
        'default': {'model': Error},
    },
    tags=['internal'],
)
def internal_delete_branch_protection_rule(
    repository: str, body: RepositoriesRepositoryBranchProtectionDeleteRequest = ...
) -> Union[None, Error]:
    pass


@app.get(
    '/repositories/{repository}/branch_protection/set_allowed',
    response_model=None,
    responses={
        '400': {'model': Error},
        '401': {'model': Error},
        '404': {'model': Error},
        '409': {'model': Error},
        'default': {'model': Error},
    },
    tags=['internal'],
)
def create_branch_protection_rule_preflight(repository: str) -> Union[None, Error]:
    pass


@app.get(
    '/repositories/{repository}/branches',
    response_model=RefList,
    responses={
        '400': {'model': Error},
        '401': {'model': Error},
        '404': {'model': Error},
        'default': {'model': Error},
    },
    tags=['branches'],
)
def list_branches(
    prefix: Optional[str] = None,
    after: Optional[str] = None,
    amount: Optional[conint(ge=-1, le=1000)] = 100,
    show_hidden: Optional[bool] = False,
    repository: str = ...,
) -> Union[RefList, Error]:
    """
    list branches
    """
    pass


@app.post(
    '/repositories/{repository}/branches',
    response_model=None,
    responses={
        '201': {'model': str},
        '400': {'model': Error},
        '401': {'model': Error},
        '403': {'model': Error},
        '404': {'model': Error},
        '409': {'model': Error},
        'default': {'model': Error},
    },
    tags=['branches'],
)
def create_branch(
    repository: str, body: BranchCreation = ...
) -> Union[None, str, Error]:
    """
    create branch
    """
    pass


@app.get(
    '/repositories/{repository}/branches/{branch}',
    response_model=Ref,
    responses={
        '400': {'model': Error},
        '401': {'model': Error},
        '404': {'model': Error},
        'default': {'model': Error},
    },
    tags=['branches'],
)
def get_branch(repository: str, branch: str = ...) -> Union[Ref, Error]:
    """
    get branch
    """
    pass


@app.delete(
    '/repositories/{repository}/branches/{branch}',
    response_model=None,
    responses={
        '400': {'model': Error},
        '401': {'model': Error},
        '403': {'model': Error},
        '404': {'model': Error},
        'default': {'model': Error},
    },
    tags=['branches'],
)
def delete_branch(
    force: Optional[bool] = False, repository: str = ..., branch: str = ...
) -> Union[None, Error]:
    """
    delete branch
    """
    pass


@app.put(
    '/repositories/{repository}/branches/{branch}',
    response_model=None,
    responses={
        '400': {'model': Error},
        '401': {'model': Error},
        '403': {'model': Error},
        '404': {'model': Error},
        'default': {'model': Error},
    },
    tags=['branches'],
)
def reset_branch(
    repository: str, branch: str = ..., body: ResetCreation = ...
) -> Union[None, Error]:
    """
    reset branch
    """
    pass


@app.post(
    '/repositories/{repository}/branches/{branch}/cherry-pick',
    response_model=None,
    responses={
        '201': {'model': Commit},
        '400': {'model': Error},
        '401': {'model': Error},
        '403': {'model': Error},
        '404': {'model': Error},
        '409': {'model': Error},
        'default': {'model': Error},
    },
    tags=['branches'],
)
def cherry_pick(
    repository: str, branch: str = ..., body: CherryPickCreation = ...
) -> Union[None, Commit, Error]:
    """
    Replay the changes from the given commit on the branch
    """
    pass


@app.post(
    '/repositories/{repository}/branches/{branch}/commits',
    response_model=None,
    responses={
        '201': {'model': Commit},
        '400': {'model': Error},
        '401': {'model': Error},
        '403': {'model': Error},
        '404': {'model': Error},
        '409': {'model': Error},
        '412': {'model': Error},
        'default': {'model': Error},
    },
    tags=['commits'],
)
def commit(
    source_metarange: Optional[str] = None,
    repository: str = ...,
    branch: str = ...,
    body: CommitCreation = ...,
) -> Union[None, Commit, Error]:
    """
    create commit
    """
    pass


@app.get(
    '/repositories/{repository}/branches/{branch}/diff',
    response_model=DiffList,
    responses={
        '400': {'model': Error},
        '401': {'model': Error},
        '404': {'model': Error},
        'default': {'model': Error},
    },
    tags=['branches'],
)
def diff_branch(
    after: Optional[str] = None,
    amount: Optional[conint(ge=-1, le=1000)] = 100,
    prefix: Optional[str] = None,
    delimiter: Optional[str] = None,
    repository: str = ...,
    branch: str = ...,
) -> Union[DiffList, Error]:
    """
    diff branch
    """
    pass


@app.put(
    '/repositories/{repository}/branches/{branch}/hard_reset',
    response_model=None,
    responses={
        '400': {'model': Error},
        '401': {'model': Error},
        '403': {'model': Error},
        '404': {'model': Error},
        'default': {'model': Error},
    },
    tags=['experimental'],
)
def hard_reset_branch(
    ref: str, force: Optional[bool] = False, repository: str = ..., branch: str = ...
) -> Union[None, Error]:
    """
    hard reset branch
    """
    pass


@app.get(
    '/repositories/{repository}/branches/{branch}/import',
    response_model=ImportStatus,
    responses={
        '400': {'model': Error},
        '401': {'model': Error},
        '404': {'model': Error},
        'default': {'model': Error},
    },
    tags=['import'],
)
def import_status(
    id: str, repository: str = ..., branch: str = ...
) -> Union[ImportStatus, Error]:
    """
    get import status
    """
    pass


@app.post(
    '/repositories/{repository}/branches/{branch}/import',
    response_model=None,
    responses={
        '202': {'model': ImportCreationResponse},
        '400': {'model': Error},
        '401': {'model': Error},
        '403': {'model': Error},
        '404': {'model': Error},
        'default': {'model': Error},
    },
    tags=['import'],
)
def import_start(
    repository: str, branch: str = ..., body: ImportCreation = ...
) -> Union[None, ImportCreationResponse, Error]:
    """
    import data from object store
    """
    pass


@app.delete(
    '/repositories/{repository}/branches/{branch}/import',
    response_model=None,
    responses={
        '400': {'model': Error},
        '401': {'model': Error},
        '403': {'model': Error},
        '404': {'model': Error},
        '409': {'model': Error},
        'default': {'model': Error},
    },
    tags=['import'],
)
def import_cancel(
    id: str, repository: str = ..., branch: str = ...
) -> Union[None, Error]:
    """
    cancel ongoing import
    """
    pass


@app.put(
    '/repositories/{repository}/branches/{branch}/objects',
    response_model=None,
    responses={
        '201': {'model': ObjectStats},
        '400': {'model': Error},
        '401': {'model': Error},
        '403': {'model': Error},
        '404': {'model': Error},
        'default': {'model': Error},
    },
    tags=['internal'],
)
def stage_object(
    repository: str, branch: str = ..., path: str = ..., body: ObjectStageCreation = ...
) -> Union[None, ObjectStats, Error]:
    """
    stage an object's metadata for the given branch
    """
    pass


@app.post(
    '/repositories/{repository}/branches/{branch}/objects',
    response_model=None,
    responses={
        '201': {'model': ObjectStats},
        '400': {'model': Error},
        '401': {'model': Error},
        '403': {'model': Error},
        '404': {'model': Error},
        '412': {'model': Error},
        '501': {'model': Error},
        'default': {'model': Error},
    },
    tags=['objects'],
)
def upload_object(
    if__none__match: Optional[str] = Header(None, alias='If-None-Match'),
    if__match: Optional[str] = Header(None, alias='If-Match'),
    storage_class: Optional[str] = Query(None, alias='storageClass'),
    force: Optional[bool] = False,
    repository: str = ...,
    branch: str = ...,
    path: str = ...,
    file: UploadFile = ...,
) -> Union[None, ObjectStats, Error]:
    pass


@app.delete(
    '/repositories/{repository}/branches/{branch}/objects',
    response_model=None,
    responses={
        '400': {'model': Error},
        '401': {'model': Error},
        '403': {'model': Error},
        '404': {'model': Error},
        'default': {'model': Error},
    },
    tags=['objects'],
)
def delete_object(
    force: Optional[bool] = False,
    no_tombstone: Optional[bool] = False,
    repository: str = ...,
    branch: str = ...,
    path: str = ...,
) -> Union[None, Error]:
    """
    delete object. Missing objects will not return a NotFound error.
    """
    pass


@app.post(
    '/repositories/{repository}/branches/{branch}/objects/copy',
    response_model=None,
    responses={
        '201': {'model': ObjectStats},
        '400': {'model': Error},
        '401': {'model': Error},
        '403': {'model': Error},
        '404': {'model': Error},
        'default': {'model': Error},
    },
    tags=['objects'],
)
def copy_object(
    repository: str,
    branch: str = ...,
    dest_path: str = ...,
    body: ObjectCopyCreation = ...,
) -> Union[None, ObjectStats, Error]:
    """
    create a copy of an object
    """
    pass


@app.post(
    '/repositories/{repository}/branches/{branch}/objects/delete',
    response_model=ObjectErrorList,
    responses={
        '400': {'model': Error},
        '401': {'model': Error},
        '403': {'model': Error},
        '404': {'model': Error},
        'default': {'model': Error},
    },
    tags=['objects'],
)
def delete_objects(
    repository: str,
    branch: str = ...,
    force: Optional[bool] = False,
    no_tombstone: Optional[bool] = False,
    body: PathList = ...,
) -> Union[ObjectErrorList, Error]:
    """
    delete objects. Missing objects will not return a NotFound error.
    """
    pass


@app.get(
    '/repositories/{repository}/branches/{branch}/objects/stage_allowed',
    response_model=None,
    responses={
        '400': {'model': Error},
        '401': {'model': Error},
        '403': {'model': Error},
        '404': {'model': Error},
        'default': {'model': Error},
    },
    tags=['internal'],
)
def upload_object_preflight(
    repository: str, branch: str = ..., path: str = ...
) -> Union[None, Error]:
    pass


@app.put(
    '/repositories/{repository}/branches/{branch}/objects/stat/user_metadata',
    response_model=None,
    responses={
        '401': {'model': Error},
        '404': {'model': Error},
        '400': {'model': Error},
        'default': {'model': Error},
    },
    tags=['objects', 'experimental'],
)
def update_object_user_metadata(
    repository: str,
    branch: str = ...,
    path: str = ...,
    body: UpdateObjectUserMetadata = ...,
) -> Union[None, Error]:
    """
    rewrite (all) object metadata
    """
    pass


@app.post(
    '/repositories/{repository}/branches/{branch}/revert',
    response_model=None,
    responses={
        '400': {'model': Error},
        '401': {'model': Error},
        '403': {'model': Error},
        '404': {'model': Error},
        '409': {'model': Error},
        'default': {'model': Error},
    },
    tags=['branches'],
)
def revert_branch(
    repository: str, branch: str = ..., body: RevertCreation = ...
) -> Union[None, Error]:
    """
    revert
    """
    pass


@app.get(
    '/repositories/{repository}/branches/{branch}/staging/backing',
    response_model=StagingLocation,
    responses={
        '400': {'model': Error},
        '401': {'model': Error},
        '404': {'model': Error},
        'default': {'model': Error},
    },
    tags=['staging'],
)
def get_physical_address(
    presign: Optional[bool] = None,
    repository: str = ...,
    branch: str = ...,
    path: str = ...,
) -> Union[StagingLocation, Error]:
    """
    generate an address to which the client can upload an object
    """
    pass


@app.put(
    '/repositories/{repository}/branches/{branch}/staging/backing',
    response_model=ObjectStats,
    responses={
        '400': {'model': Error},
        '401': {'model': Error},
        '403': {'model': Error},
        '404': {'model': Error},
        '409': {'model': StagingLocation},
        '412': {'model': Error},
        '501': {'model': Error},
        'default': {'model': Error},
    },
    tags=['staging'],
)
def link_physical_address(
    if__none__match: Optional[str] = Header(None, alias='If-None-Match'),
    if__match: Optional[str] = Header(None, alias='If-Match'),
    repository: str = ...,
    branch: str = ...,
    path: str = ...,
    body: StagingMetadata = ...,
) -> Union[ObjectStats, Error, StagingLocation]:
    """
    associate staging on this physical address with a path
    """
    pass


@app.post(
    '/repositories/{repository}/branches/{branch}/staging/pmpu',
    response_model=None,
    responses={
        '201': {'model': PresignMultipartUpload},
        '400': {'model': Error},
        '401': {'model': Error},
        '404': {'model': Error},
        'default': {'model': Error},
    },
    tags=['experimental'],
)
def create_presign_multipart_upload(
    repository: str, branch: str = ..., path: str = ..., parts: Optional[int] = None
) -> Union[None, PresignMultipartUpload, Error]:
    """
    Initiate a multipart upload
    """
    pass


@app.put(
    '/repositories/{repository}/branches/{branch}/staging/pmpu/{uploadId}',
    response_model=ObjectStats,
    responses={
        '400': {'model': Error},
        '401': {'model': Error},
        '404': {'model': Error},
        '409': {'model': StagingLocation},
        'default': {'model': Error},
    },
    tags=['experimental'],
)
def complete_presign_multipart_upload(
    repository: str,
    branch: str = ...,
    upload_id: str = Path(..., alias='uploadId'),
    path: str = ...,
    body: CompletePresignMultipartUpload = None,
) -> Union[ObjectStats, Error, StagingLocation]:
    """
    Complete a presign multipart upload request
    """
    pass


@app.delete(
    '/repositories/{repository}/branches/{branch}/staging/pmpu/{uploadId}',
    response_model=None,
    responses={
        '400': {'model': Error},
        '401': {'model': Error},
        '404': {'model': Error},
        'default': {'model': Error},
    },
    tags=['experimental'],
)
def abort_presign_multipart_upload(
    repository: str,
    branch: str = ...,
    upload_id: str = Path(..., alias='uploadId'),
    path: str = ...,
    body: AbortPresignMultipartUpload = None,
) -> Union[None, Error]:
    """
    Abort a presign multipart upload
    """
    pass


@app.put(
    '/repositories/{repository}/branches/{branch}/staging/pmpu/{uploadId}/parts/{partNumber}',
    response_model=UploadTo,
    responses={
        '400': {'model': Error},
        '401': {'model': Error},
        '404': {'model': Error},
        'default': {'model': Error},
    },
    tags=['experimental'],
)
def upload_part(
    repository: str,
    branch: str = ...,
    upload_id: str = Path(..., alias='uploadId'),
    path: str = ...,
    part_number: conint(ge=1, le=10000) = Path(..., alias='partNumber'),
    body: UploadPartFrom = ...,
) -> Union[UploadTo, Error]:
    pass


@app.put(
    '/repositories/{repository}/branches/{branch}/staging/pmpu/{uploadId}/parts/{partNumber}/copy',
    response_model=None,
    responses={
        '400': {'model': Error},
        '401': {'model': Error},
        '404': {'model': Error},
        'default': {'model': Error},
    },
    tags=['experimental'],
)
def upload_part_copy(
    repository: str,
    branch: str = ...,
    upload_id: str = Path(..., alias='uploadId'),
    path: str = ...,
    part_number: conint(ge=1, le=10000) = Path(..., alias='partNumber'),
    body: UploadPartCopyFrom = ...,
) -> Union[None, Error]:
    pass


@app.post(
    '/repositories/{repository}/commits',
    response_model=None,
    responses={
        '400': {'model': Error},
        '401': {'model': Error},
        '403': {'model': Error},
        '404': {'model': Error},
        'default': {'model': Error},
    },
    tags=['internal'],
)
def create_commit_record(
    repository: str, body: CommitRecordCreation = ...
) -> Union[None, Error]:
    """
    create commit record
    """
    pass


@app.get(
    '/repositories/{repository}/commits/{commitId}',
    response_model=Commit,
    responses={
        '400': {'model': Error},
        '401': {'model': Error},
        '404': {'model': Error},
        'default': {'model': Error},
    },
    tags=['commits'],
)
def get_commit(
    repository: str, commit_id: str = Path(..., alias='commitId')
) -> Union[Commit, Error]:
    """
    get commit
    """
    pass


@app.post(
    '/repositories/{repository}/dump',
    response_model=None,
    responses={
        '202': {'model': TaskInfo},
        '400': {'model': Error},
        '401': {'model': Error},
        '404': {'model': Error},
        'default': {'model': Error},
    },
    tags=['repositories'],
)
def dump_submit(repository: str) -> Union[None, TaskInfo, Error]:
    """
    Backup the repository metadata (tags, commits, branches) and save the backup to the object store.
    """
    pass


@app.get(
    '/repositories/{repository}/dump',
    response_model=RepositoryDumpStatus,
    responses={
        '400': {'model': Error},
        '401': {'model': Error},
        '404': {'model': Error},
        'default': {'model': Error},
    },
    tags=['repositories'],
)
def dump_status(
    task_id: str, repository: str = ...
) -> Union[RepositoryDumpStatus, Error]:
    """
    Status of a repository dump task
    """
    pass


@app.post(
    '/repositories/{repository}/gc/prepare_commits',
    response_model=None,
    responses={
        '201': {'model': GarbageCollectionPrepareResponse},
        '400': {'model': Error},
        '401': {'model': Error},
        '403': {'model': Error},
        '404': {'model': Error},
        'default': {'model': Error},
    },
    tags=['internal'],
)
def prepare_garbage_collection_commits(
    repository: str,
) -> Union[None, GarbageCollectionPrepareResponse, Error]:
    """
    save lists of active commits for garbage collection
    """
    pass


@app.post(
    '/repositories/{repository}/gc/prepare_commits/async',
    response_model=None,
    responses={
        '202': {'model': TaskCreation},
        '400': {'model': Error},
        '401': {'model': Error},
        '403': {'model': Error},
        '404': {'model': Error},
        'default': {'model': Error},
    },
    tags=['internal'],
)
def prepare_garbage_collection_commits_async(
    repository: str,
) -> Union[None, TaskCreation, Error]:
    """
    prepare gc commits
    """
    pass


@app.get(
    '/repositories/{repository}/gc/prepare_commits/status',
    response_model=PrepareGarbageCollectionCommitsStatus,
    responses={
        '400': {'model': Error},
        '401': {'model': Error},
        '403': {'model': Error},
        '404': {'model': Error},
        'default': {'model': Error},
    },
    tags=['internal'],
)
def prepare_garbage_collection_commits_status(
    id: str, repository: str = ...
) -> Union[PrepareGarbageCollectionCommitsStatus, Error]:
    """
    get status of prepare gc commits operation
    """
    pass


@app.post(
    '/repositories/{repository}/gc/prepare_uncommited',
    response_model=None,
    responses={
        '201': {'model': PrepareGCUncommittedResponse},
        '400': {'model': Error},
        '401': {'model': Error},
        '403': {'model': Error},
        '404': {'model': Error},
        'default': {'model': Error},
    },
    tags=['internal'],
)
def prepare_garbage_collection_uncommitted(
    repository: str, body: PrepareGCUncommittedRequest = None
) -> Union[None, PrepareGCUncommittedResponse, Error]:
    """
    save repository uncommitted metadata for garbage collection
    """
    pass


@app.get(
    '/repositories/{repository}/gc/rules',
    response_model=GarbageCollectionRules,
    responses={
        '400': {'model': Error},
        '401': {'model': Error},
        '404': {'model': Error},
        'default': {'model': Error},
    },
    tags=['internal'],
)
def internal_get_garbage_collection_rules(
    repository: str,
) -> Union[GarbageCollectionRules, Error]:
    pass


@app.post(
    '/repositories/{repository}/gc/rules',
    response_model=None,
    responses={
        '400': {'model': Error},
        '401': {'model': Error},
        '404': {'model': Error},
        'default': {'model': Error},
    },
    tags=['internal'],
)
def internal_set_garbage_collection_rules(
    repository: str, body: GarbageCollectionRules = ...
) -> Union[None, Error]:
    pass


@app.delete(
    '/repositories/{repository}/gc/rules',
    response_model=None,
    responses={
        '400': {'model': Error},
        '401': {'model': Error},
        '404': {'model': Error},
        'default': {'model': Error},
    },
    tags=['internal'],
)
def internal_delete_garbage_collection_rules(repository: str) -> Union[None, Error]:
    pass


@app.get(
    '/repositories/{repository}/gc/rules/set_allowed',
    response_model=None,
    responses={
        '400': {'model': Error},
        '401': {'model': Error},
        '404': {'model': Error},
        'default': {'model': Error},
    },
    tags=['internal'],
)
def set_garbage_collection_rules_preflight(repository: str) -> Union[None, Error]:
    pass


@app.get(
    '/repositories/{repository}/metadata',
    response_model=RepositoryMetadata,
    responses={
        '400': {'model': Error},
        '401': {'model': Error},
        '404': {'model': Error},
        'default': {'model': Error},
    },
    tags=['repositories'],
)
def get_repository_metadata(repository: str) -> Union[RepositoryMetadata, Error]:
    """
    get repository metadata
    """
    pass


@app.post(
    '/repositories/{repository}/metadata',
    response_model=None,
    responses={
        '400': {'model': Error},
        '401': {'model': Error},
        '404': {'model': Error},
        'default': {'model': Error},
    },
    tags=['internal'],
)
def set_repository_metadata(
    repository: str, body: RepositoryMetadataSet = ...
) -> Union[None, Error]:
    """
    set repository metadata
    """
    pass


@app.delete(
    '/repositories/{repository}/metadata',
    response_model=None,
    responses={
        '400': {'model': Error},
        '401': {'model': Error},
        'default': {'model': Error},
    },
    tags=['internal'],
)
def delete_repository_metadata(
    repository: str, body: RepositoryMetadataKeys = ...
) -> Union[None, Error]:
    """
    delete repository metadata
    """
    pass


@app.get(
    '/repositories/{repository}/metadata/meta_range/{meta_range}',
    response_model=StorageURI,
    responses={
        '400': {'model': Error},
        '401': {'model': Error},
        '404': {'model': Error},
        'default': {'model': Error},
    },
    tags=['metadata'],
)
def get_meta_range(repository: str, meta_range: str = ...) -> Union[StorageURI, Error]:
    """
    return URI to a meta-range file
    """
    pass


@app.get(
    '/repositories/{repository}/metadata/object/{type}/{object_id}',
    response_model=bytes,
    responses={
        '400': {'model': Error},
        '401': {'model': Error},
        '404': {'model': Error},
        'default': {'model': Error},
    },
    tags=['internal'],
)
def get_metadata_object(
    presign: Optional[bool] = None,
    repository: str = ...,
    object_id: str = ...,
    type: Type6 = ...,
) -> Union[bytes, Error]:
    """
    return a lakeFS metadata object by ID
    """
    pass


@app.get(
    '/repositories/{repository}/metadata/range/{range}',
    response_model=StorageURI,
    responses={
        '400': {'model': Error},
        '401': {'model': Error},
        '404': {'model': Error},
        'default': {'model': Error},
    },
    tags=['metadata'],
)
def get_range(repository: str, range: str = ...) -> Union[StorageURI, Error]:
    """
    return URI to a range file
    """
    pass


@app.get(
    '/repositories/{repository}/pulls',
    response_model=PullRequestsList,
    responses={
        '400': {'model': Error},
        '401': {'model': Error},
        '404': {'model': Error},
        'default': {'model': Error},
    },
    tags=['pulls', 'experimental'],
)
def list_pull_requests(
    prefix: Optional[str] = None,
    after: Optional[str] = None,
    amount: Optional[conint(ge=-1, le=1000)] = 100,
    status: Optional[Status4] = 'all',
    repository: str = ...,
) -> Union[PullRequestsList, Error]:
    """
    list pull requests
    """
    pass


@app.post(
    '/repositories/{repository}/pulls',
    response_model=None,
    responses={
        '201': {'model': PullRequestCreationResponse},
        '400': {'model': Error},
        '401': {'model': Error},
        '403': {'model': Error},
        '404': {'model': Error},
        '409': {'model': Error},
        'default': {'model': Error},
    },
    tags=['pulls', 'experimental'],
)
def create_pull_request(
    repository: str, body: PullRequestCreation = ...
) -> Union[None, PullRequestCreationResponse, Error]:
    """
    create pull request
    """
    pass


@app.get(
    '/repositories/{repository}/pulls/{pull_request}',
    response_model=PullRequest,
    responses={
        '400': {'model': Error},
        '401': {'model': Error},
        '404': {'model': Error},
        'default': {'model': Error},
    },
    tags=['pulls', 'experimental'],
)
def get_pull_request(
    repository: str, pull_request: str = ...
) -> Union[PullRequest, Error]:
    """
    get pull request
    """
    pass


@app.patch(
    '/repositories/{repository}/pulls/{pull_request}',
    response_model=None,
    responses={
        '400': {'model': Error},
        '401': {'model': Error},
        '403': {'model': Error},
        '404': {'model': Error},
        'default': {'model': Error},
    },
    tags=['pulls', 'experimental'],
)
def update_pull_request(
    repository: str, pull_request: str = ..., body: PullRequestBasic = ...
) -> Union[None, Error]:
    """
    update pull request
    """
    pass


@app.put(
    '/repositories/{repository}/pulls/{pull_request}/merge',
    response_model=MergeResult,
    responses={
        '400': {'model': Error},
        '401': {'model': Error},
        '403': {'model': Error},
        '404': {'model': Error},
        '409': {'model': MergeResult},
        '412': {'model': Error},
        'default': {'model': Error},
    },
    tags=['pulls', 'experimental'],
)
def merge_pull_request(
    repository: str, pull_request: str = ...
) -> Union[MergeResult, Error]:
    """
    merge pull request
    """
    pass


@app.put(
    '/repositories/{repository}/refs/dump',
    response_model=None,
    responses={
        '201': {'model': RefsDump},
        '400': {'model': Error},
        '401': {'model': Error},
        '404': {'model': Error},
        'default': {'model': Error},
    },
    tags=['internal'],
)
def dump_refs(repository: str) -> Union[None, RefsDump, Error]:
    """
        Dump repository refs (tags, commits, branches) to object store
    Deprecated: a new API will introduce long running operations

    """
    pass


@app.put(
    '/repositories/{repository}/refs/restore',
    response_model=None,
    responses={
        '400': {'model': Error},
        '401': {'model': Error},
        '404': {'model': Error},
        'default': {'model': Error},
    },
    tags=['internal'],
)
def restore_refs(repository: str, body: RefsRestore = ...) -> Union[None, Error]:
    """
        Restore repository refs (tags, commits, branches) from object store.
    Deprecated: a new API will introduce long running operations

    """
    pass


@app.post(
    '/repositories/{repository}/refs/{branch}/symlink',
    response_model=None,
    responses={
        '201': {'model': StorageURI},
        '400': {'model': Error},
        '401': {'model': Error},
        '404': {'model': Error},
        'default': {'model': Error},
    },
    tags=['internal'],
)
def create_symlink_file(
    repository: str, branch: str = ..., location: Optional[str] = None
) -> Union[None, StorageURI, Error]:
    """
    creates symlink files corresponding to the given directory
    """
    pass


@app.get(
    '/repositories/{repository}/refs/{leftRef}/diff/{rightRef}',
    response_model=DiffList,
    responses={
        '400': {'model': Error},
        '401': {'model': Error},
        '404': {'model': Error},
        'default': {'model': Error},
    },
    tags=['refs'],
)
def diff_refs(
    repository: str,
    left_ref: str = Path(..., alias='leftRef'),
    right_ref: str = Path(..., alias='rightRef'),
    after: Optional[str] = None,
    amount: Optional[conint(ge=-1, le=1000)] = 100,
    prefix: Optional[str] = None,
    delimiter: Optional[str] = None,
    type: Optional[Type4] = 'three_dot',
    include_right_stats: Optional[bool] = False,
) -> Union[DiffList, Error]:
    """
    diff references
    """
    pass


@app.get(
    '/repositories/{repository}/refs/{ref}/commits',
    response_model=CommitList,
    responses={
        '400': {'model': Error},
        '401': {'model': Error},
        '404': {'model': Error},
        'default': {'model': Error},
    },
    tags=['refs'],
)
def log_commits(
    after: Optional[str] = None,
    amount: Optional[conint(ge=-1, le=1000)] = 100,
    objects: Optional[List[str]] = None,
    prefixes: Optional[List[str]] = None,
    limit: Optional[bool] = None,
    first_parent: Optional[bool] = None,
    since: Optional[datetime] = None,
    stop_at: Optional[str] = None,
    repository: str = ...,
    ref: str = ...,
) -> Union[CommitList, Error]:
    """
    get commit log from ref. If both objects and prefixes are empty, return all commits.
    """
    pass


@app.get(
    '/repositories/{repository}/refs/{ref}/objects',
    response_model=bytes,
    responses={
        '206': {'model': bytes},
        '400': {'model': Error},
        '401': {'model': Error},
        '404': {'model': Error},
        '410': {'model': Error},
        '416': {'model': Error},
        'default': {'model': Error},
    },
    tags=['objects'],
)
def get_object(
    range: Optional[constr(regex=r'^bytes=((\d*-\d*,? ?)+)$')] = Header(
        None, alias='Range'
    ),
    if__none__match: Optional[str] = Header(None, alias='If-None-Match'),
    presign: Optional[bool] = None,
    repository: str = ...,
    ref: str = ...,
    path: str = ...,
) -> Union[bytes, Error]:
    """
    get object content
    """
    pass


@app.head(
    '/repositories/{repository}/refs/{ref}/objects',
    response_model=None,
    tags=['objects'],
)
def head_object(
    range: Optional[constr(regex=r'^bytes=((\d*-\d*,? ?)+)$')] = Header(
        None, alias='Range'
    ),
    repository: str = ...,
    ref: str = ...,
    path: str = ...,
) -> None:
    """
    check if object exists
    """
    pass


@app.get(
    '/repositories/{repository}/refs/{ref}/objects/ls',
    response_model=ObjectStatsList,
    responses={
        '400': {'model': Error},
        '401': {'model': Error},
        '404': {'model': Error},
        'default': {'model': Error},
    },
    tags=['objects'],
)
def list_objects(
    repository: str,
    ref: str = ...,
    user_metadata: Optional[bool] = True,
    presign: Optional[bool] = None,
    after: Optional[str] = None,
    amount: Optional[conint(ge=-1, le=1000)] = 100,
    delimiter: Optional[str] = None,
    prefix: Optional[str] = None,
) -> Union[ObjectStatsList, Error]:
    """
    list objects under a given prefix
    """
    pass


@app.get(
    '/repositories/{repository}/refs/{ref}/objects/stat',
    response_model=ObjectStats,
    responses={
        '401': {'model': Error},
        '404': {'model': Error},
        '400': {'model': Error},
        'default': {'model': Error},
    },
    tags=['objects'],
)
def stat_object(
    repository: str,
    ref: str = ...,
    path: str = ...,
    user_metadata: Optional[bool] = True,
    presign: Optional[bool] = None,
) -> Union[ObjectStats, Error]:
    """
    get object metadata
    """
    pass


@app.get(
    '/repositories/{repository}/refs/{ref}/objects/underlyingProperties',
    response_model=UnderlyingObjectProperties,
    responses={
        '400': {'model': Error},
        '401': {'model': Error},
        '404': {'model': Error},
        'default': {'model': Error},
    },
    tags=['objects'],
)
def get_underlying_properties(
    repository: str, ref: str = ..., path: str = ...
) -> Union[UnderlyingObjectProperties, Error]:
    """
    get object properties on underlying storage
    """
    pass


@app.post(
    '/repositories/{repository}/refs/{sourceRef}/merge/{destinationBranch}',
    response_model=MergeResult,
    responses={
        '400': {'model': Error},
        '401': {'model': Error},
        '403': {'model': Error},
        '404': {'model': Error},
        '409': {'model': MergeResult},
        '412': {'model': Error},
        'default': {'model': Error},
    },
    tags=['refs'],
)
def merge_into_branch(
    repository: str,
    source_ref: str = Path(..., alias='sourceRef'),
    destination_branch: str = Path(..., alias='destinationBranch'),
    body: Merge = None,
) -> Union[MergeResult, Error]:
    """
    merge references
    """
    pass


@app.get(
    '/repositories/{repository}/refs/{sourceRef}/merge/{destinationBranch}',
    response_model=FindMergeBaseResult,
    responses={
        '400': {'model': Error},
        '401': {'model': Error},
        '404': {'model': Error},
        'default': {'model': Error},
    },
    tags=['refs'],
)
def find_merge_base(
    repository: str,
    source_ref: str = Path(..., alias='sourceRef'),
    destination_branch: str = Path(..., alias='destinationBranch'),
) -> Union[FindMergeBaseResult, Error]:
    """
    find the merge base for 2 references
    """
    pass


@app.post(
    '/repositories/{repository}/restore',
    response_model=None,
    responses={
        '202': {'model': TaskInfo},
        '400': {'model': Error},
        '403': {'model': Error},
        '401': {'model': Error},
        '404': {'model': Error},
        'default': {'model': Error},
    },
    tags=['repositories'],
)
def restore_submit(
    repository: str, body: RefsRestore = ...
) -> Union[None, TaskInfo, Error]:
    """
    Restore repository from a dump in the object store
    """
    pass


@app.get(
    '/repositories/{repository}/restore',
    response_model=RepositoryRestoreStatus,
    responses={
        '400': {'model': Error},
        '401': {'model': Error},
        '404': {'model': Error},
        'default': {'model': Error},
    },
    tags=['repositories'],
)
def restore_status(
    task_id: str, repository: str = ...
) -> Union[RepositoryRestoreStatus, Error]:
    """
    Status of a restore request
    """
    pass


@app.get(
    '/repositories/{repository}/settings/branch_protection',
    response_model=List[BranchProtectionRule],
    responses={
        '400': {'model': Error},
        '401': {'model': Error},
        '404': {'model': Error},
        'default': {'model': Error},
    },
    tags=['repositories'],
)
def get_branch_protection_rules(
    repository: str,
) -> Union[List[BranchProtectionRule], Error]:
    """
    get branch protection rules
    """
    pass


@app.put(
    '/repositories/{repository}/settings/branch_protection',
    response_model=None,
    responses={
        '400': {'model': Error},
        '401': {'model': Error},
        '403': {'model': Error},
        '404': {'model': Error},
        '412': {'model': Error},
        'default': {'model': Error},
    },
    tags=['repositories'],
)
def set_branch_protection_rules(
    if__match: Optional[str] = Header(None, alias='If-Match'),
    repository: str = ...,
    body: List[BranchProtectionRule] = ...,
) -> Union[None, Error]:
    pass


@app.get(
    '/repositories/{repository}/settings/gc_rules',
    response_model=GarbageCollectionRules,
    responses={
        '400': {'model': Error},
        '401': {'model': Error},
        '404': {'model': Error},
        'default': {'model': Error},
    },
    tags=['repositories'],
)
def get_g_c_rules(repository: str) -> Union[GarbageCollectionRules, Error]:
    """
    get repository GC rules
    """
    pass


@app.put(
    '/repositories/{repository}/settings/gc_rules',
    response_model=None,
    responses={
        '400': {'model': Error},
        '401': {'model': Error},
        '403': {'model': Error},
        '404': {'model': Error},
        'default': {'model': Error},
    },
    tags=['repositories'],
)
def set_g_c_rules(
    repository: str, body: GarbageCollectionRules = ...
) -> Union[None, Error]:
    pass


@app.delete(
    '/repositories/{repository}/settings/gc_rules',
    response_model=None,
    responses={
        '400': {'model': Error},
        '401': {'model': Error},
        '403': {'model': Error},
        '404': {'model': Error},
        'default': {'model': Error},
    },
    tags=['repositories'],
)
def delete_g_c_rules(repository: str) -> Union[None, Error]:
    pass


@app.get(
    '/repositories/{repository}/tags',
    response_model=RefList,
    responses={
        '400': {'model': Error},
        '401': {'model': Error},
        '404': {'model': Error},
        'default': {'model': Error},
    },
    tags=['tags'],
)
def list_tags(
    prefix: Optional[str] = None,
    after: Optional[str] = None,
    amount: Optional[conint(ge=-1, le=1000)] = 100,
    repository: str = ...,
) -> Union[RefList, Error]:
    """
    list tags
    """
    pass


@app.post(
    '/repositories/{repository}/tags',
    response_model=None,
    responses={
        '201': {'model': Ref},
        '400': {'model': Error},
        '401': {'model': Error},
        '403': {'model': Error},
        '404': {'model': Error},
        '409': {'model': Error},
        'default': {'model': Error},
    },
    tags=['tags'],
)
def create_tag(repository: str, body: TagCreation = ...) -> Union[None, Ref, Error]:
    """
    create tag
    """
    pass


@app.get(
    '/repositories/{repository}/tags/{tag}',
    response_model=Ref,
    responses={
        '400': {'model': Error},
        '401': {'model': Error},
        '404': {'model': Error},
        'default': {'model': Error},
    },
    tags=['tags'],
)
def get_tag(repository: str, tag: str = ...) -> Union[Ref, Error]:
    """
    get tag
    """
    pass


@app.delete(
    '/repositories/{repository}/tags/{tag}',
    response_model=None,
    responses={
        '400': {'model': Error},
        '401': {'model': Error},
        '403': {'model': Error},
        '404': {'model': Error},
        'default': {'model': Error},
    },
    tags=['tags'],
)
def delete_tag(
    force: Optional[bool] = None, repository: str = ..., tag: str = ...
) -> Union[None, Error]:
    """
    delete tag
    """
    pass


@app.post(
    '/setup_comm_prefs',
    response_model=None,
    responses={
        '400': {'model': Error},
        '409': {'model': Error},
        '412': {'model': Error},
        'default': {'model': Error},
    },
    tags=['internal'],
)
def setup_comm_prefs(body: CommPrefsInput) -> Union[None, Error]:
    """
    setup communications preferences
    """
    pass


@app.get(
    '/setup_lakefs',
    response_model=SetupState,
    responses={'default': {'model': Error}},
    tags=['internal'],
)
def get_setup_state() -> Union[SetupState, Error]:
    """
    check if the lakeFS installation is already set up
    """
    pass


@app.post(
    '/setup_lakefs',
    response_model=CredentialsWithSecret,
    responses={
        '400': {'model': Error},
        '409': {'model': Error},
        'default': {'model': Error},
    },
    tags=['internal'],
)
def setup(body: Setup) -> Union[CredentialsWithSecret, Error]:
    """
    setup lakeFS and create a first user
    """
    pass


@app.post(
    '/statistics',
    response_model=None,
    responses={
        '400': {'model': Error},
        '401': {'model': Error},
        'default': {'model': Error},
    },
    tags=['internal'],
)
def post_stats_events(body: StatsEventsList) -> Union[None, Error]:
    """
    post stats events, this endpoint is meant for internal use only
    """
    pass


@app.post(
    '/sts/login',
    response_model=AuthenticationToken,
    responses={
        '400': {'model': Error},
        '401': {'model': Error},
        'default': {'model': Error},
    },
    tags=['experimental'],
)
def sts_login(body: StsAuthRequest) -> Union[AuthenticationToken, Error]:
    """
    perform a login with STS
    """
    pass


@app.get(
    '/usage-report/summary',
    response_model=InstallationUsageReport,
    responses={
        '401': {'model': Error},
        '404': {'model': Error},
        'default': {'model': Error},
    },
    tags=['internal'],
)
def get_usage_report_summary() -> Union[InstallationUsageReport, Error]:
    """
    get usage report summary
    """
    pass


@app.get('/user', response_model=CurrentUser, tags=['auth'])
def get_current_user() -> CurrentUser:
    """
    get current user
    """
    pass
