# generated by fastapi-codegen:
#   filename:  swagger.yml
#   timestamp: 2026-04-30T12:03:51+00:00

from __future__ import annotations

from fastapi import FastAPI, Request
from fastapi.responses import Response, JSONResponse
from lakefs_sdk.exceptions import ApiException

from .routes.auth.api import app as auth_router
from .routes.repos.api import app as repos_router
from .routes.objects.api import app as objects_router
from .routes.setup import app as setup_router
from .routes.config import app as config_router
from .routes.gc import app as gc_router


app = FastAPI(
    description='lakeFS HTTP API',
    title='lakeFS API',
    license={
        'name': 'Apache 2.0',
        'url': 'https://www.apache.org/licenses/LICENSE-2.0.html',
    },
    version='1.0.0',
    servers=[{'url': '/api/v1', 'description': 'lakeFS server endpoint'}],
)

app.router.prefix = '/api/v1'

routers = [auth_router, repos_router, objects_router, setup_router]

for router in routers:
    app.include_router(router)


@app.get('/healthcheck', response_model=None, tags=['healthCheck'])
def health_check() -> None:
    pass


@app.exception_handler(ApiException)
async def lakefs_error_handler(request: Request, exc: ApiException):
    return Response(
        content=exc.body,
        status_code=exc.status,
        media_type="application/json"
    )

@app.exception_handler(NotImplementedError)
async def not_implemented_handler(request, exc):
    return JSONResponse(
        status_code=501,
        content={"message": "This action is currently not supported by the wrapper."},
    )