# generated by fastapi-codegen:
#   filename:  /local/swagger.yml
#   timestamp: 2026-04-30T12:03:51+00:00

from __future__ import annotations

from datetime import datetime
from enum import Enum
from typing import Any, Dict, List, Optional, Union

from pydantic import BaseModel, Field, RootModel, conint, constr


class Pagination(BaseModel):
    has_more: bool = Field(..., description='Next page is available')
    next_offset: str = Field(..., description='Token used to retrieve the next page')
    results: conint(ge=0) = Field(
        ..., description='Number of values found in the results'
    )
    max_per_page: conint(ge=0) = Field(
        ..., description='Maximal number of entries per page'
    )


class Repository(BaseModel):
    id: str
    creation_date: int = Field(..., description='Unix Epoch in seconds')
    default_branch: str
    storage_id: Optional[str] = Field(
        None,
        description='Unique identifier of the underlying data store. *EXPERIMENTAL*',
    )
    storage_namespace: str = Field(
        ...,
        description='Filesystem URI to store the underlying data in (e.g. "s3://my-bucket/some/path/")',
    )
    read_only: Optional[bool] = Field(
        None,
        description='Whether the repository is a read-only repository- not relevant for bare repositories',
    )


class RepositoryMetadata(RootModel[Optional[Dict[str, str]]]):
    pass


class RepositoryMetadataSet(BaseModel):
    metadata: Dict[str, str]


class RepositoryMetadataKeys(BaseModel):
    keys: List[str]


class RepositoryList(BaseModel):
    pagination: Pagination
    results: List[Repository]


class FindMergeBaseResult(BaseModel):
    source_commit_id: str = Field(..., description='The commit ID of the merge source')
    destination_commit_id: str = Field(
        ..., description='The commit ID of the merge destination'
    )
    base_commit_id: str = Field(..., description='The commit ID of the merge base')


class MergeResult(BaseModel):
    reference: str


class RepositoryCreation(BaseModel):
    name: constr(pattern=r'^[a-z0-9][a-z0-9-]{2,62}$')
    storage_id: Optional[str] = Field(
        None,
        description='Unique identifier of the underlying data store. *EXPERIMENTAL*',
    )
    storage_namespace: constr(
        pattern=r'^(s3|gs|https?|mem|local|transient)://.*$'
    ) = Field(
        ...,
        description='Filesystem URI to store the underlying data in (e.g. "s3://my-bucket/some/path/")',
        example='s3://example-bucket/',
    )
    default_branch: Optional[str] = Field(None, example='main')
    sample_data: Optional[bool] = Field(False, example=True)
    read_only: Optional[bool] = Field(False, example=True)


class PathList(BaseModel):
    paths: List[str]


class PathType(Enum):
    common_prefix = 'common_prefix'
    object = 'object'


class ObjectCopyCreation(BaseModel):
    src_path: str = Field(
        ..., description='path of the copied object relative to the ref'
    )
    src_ref: Optional[str] = Field(
        None, description='a reference, if empty uses the provided branch as ref'
    )
    force: Optional[bool] = False
    shallow: Optional[bool] = Field(
        False,
        description='Create a shallow copy of the object (without copying the actual data). At the moment shallow copy only works for same repository and branch. \nPlease note that shallow copied objects might be in contention with garbage collection and branch retention policies - use with caution.\n',
    )


class ObjectUserMetadata(RootModel[Optional[Dict[str, str]]]):
    pass


class UnderlyingObjectProperties(BaseModel):
    storage_class: Optional[str] = None


class Ref(BaseModel):
    id: str
    commit_id: str


class RefList(BaseModel):
    pagination: Pagination
    results: List[Ref]


class Type(Enum):
    added = 'added'
    removed = 'removed'
    changed = 'changed'
    conflict = 'conflict'
    prefix_changed = 'prefix_changed'


class PathType1(Enum):
    common_prefix = 'common_prefix'
    object = 'object'


class Type1(Enum):
    object = 'object'
    common_prefix = 'common_prefix'
    reset = 'reset'


class ResetCreation(BaseModel):
    type: Type1 = Field(..., description='What to reset according to path.')
    path: Optional[str] = None
    force: Optional[bool] = False


class CommitOverrides(BaseModel):
    message: Optional[str] = Field(None, description='replace the commit message')
    metadata: Optional[Dict[str, str]] = Field(
        None, description='replace the metadata of the commit'
    )


class RevertCreation(BaseModel):
    ref: str = Field(..., description='the commit to revert, given by a ref')
    commit_overrides: Optional[CommitOverrides] = None
    parent_number: int = Field(
        ...,
        description='when reverting a merge commit, the parent number (starting from 1) relative to which to perform the revert.',
    )
    force: Optional[bool] = False
    allow_empty: Optional[bool] = Field(
        False, description='allow empty commit (revert without changes)'
    )


class CherryPickCreation(BaseModel):
    ref: str = Field(..., description='the commit to cherry-pick, given by a ref')
    parent_number: Optional[int] = Field(
        None,
        description='When cherry-picking a merge commit, the parent number (starting from 1) with which to perform the diff.\nThe default branch is parent 1.\n',
    )
    commit_overrides: Optional[CommitOverrides] = None
    force: Optional[bool] = False


class Commit(BaseModel):
    id: str
    parents: List[str]
    committer: str
    message: str
    creation_date: int = Field(..., description='Unix Epoch in seconds')
    meta_range_id: str
    metadata: Optional[Dict[str, str]] = None
    generation: Optional[int] = None
    version: Optional[conint(ge=0, le=1)] = None


class CommitList(BaseModel):
    pagination: Pagination
    results: List[Commit]


class CommitCreation(BaseModel):
    message: str
    metadata: Optional[Dict[str, str]] = None
    date: Optional[int] = Field(
        None,
        description='set date to override creation date in the commit (Unix Epoch in seconds)',
    )
    allow_empty: Optional[bool] = Field(
        False, description='sets whether a commit can contain no changes'
    )
    force: Optional[bool] = False


class CommitRecordCreation(BaseModel):
    commit_id: str = Field(..., description='id of the commit record')
    version: conint(ge=0, le=1) = Field(..., description='version of the commit record')
    committer: str = Field(..., description='committer of the commit record')
    message: str = Field(..., description='message of the commit record')
    metarange_id: str = Field(..., description='metarange_id of the commit record')
    creation_date: int = Field(..., description='Unix Epoch in seconds')
    parents: List[str] = Field(..., description='parents of the commit record')
    metadata: Optional[Dict[str, str]] = Field(
        None, description='metadata of the commit record'
    )
    generation: int = Field(..., description='generation of the commit record')
    force: Optional[bool] = False


class Merge(BaseModel):
    message: Optional[str] = None
    metadata: Optional[Dict[str, str]] = None
    strategy: Optional[str] = Field(
        None,
        description="In case of a merge conflict, this option will force the merge process to automatically favor changes from the dest branch ('dest-wins') or from the source branch('source-wins'). In case no selection is made, the merge process will fail in case of a conflict",
    )
    force: Optional[bool] = Field(
        False,
        description='Allow merge into a read-only branch or into a branch with the same content',
    )
    allow_empty: Optional[bool] = Field(
        False, description='Allow merge when the branches have the same content'
    )
    squash_merge: Optional[bool] = Field(
        False,
        description='If set, set only the destination branch as a parent, which "squashes" the merge to\nappear as a single commit on the destination branch.  The source commit is no longer\na part of the merge commit; consider adding it to the \'metadata\' or \'message\'\nfields.  This behaves like a GitHub or GitLab "squash merge", or in Git terms \'git\nmerge --squash; git commit ...\'.\n',
    )


class BranchCreation(BaseModel):
    name: str
    source: str
    force: Optional[bool] = False
    hidden: Optional[bool] = Field(
        False,
        description='When set, branch will not show up when listing branches by default. *EXPERIMENTAL*',
    )


class TagCreation(BaseModel):
    id: str = Field(..., description='ID of tag to create')
    ref: str = Field(..., description='the commit to tag')
    force: Optional[bool] = False


class TaskInfo(BaseModel):
    id: str = Field(..., description='ID of the task')


class RepositoryRestoreStatus(BaseModel):
    id: str = Field(..., description='ID of the task')
    done: bool
    update_time: datetime
    error: Optional[str] = None


class RefsDump(BaseModel):
    commits_meta_range_id: str
    tags_meta_range_id: str
    branches_meta_range_id: str


class RefsRestore(BaseModel):
    commits_meta_range_id: str
    tags_meta_range_id: str
    branches_meta_range_id: str
    force: Optional[bool] = False


class StorageURI(BaseModel):
    location: str


class Error(BaseModel):
    message: str = Field(..., description='short message explaining the error')


class ObjectError(BaseModel):
    status_code: int = Field(
        ..., description='HTTP status code associated for operation on path'
    )
    message: str = Field(..., description='short message explaining status_code')
    path: Optional[str] = Field(None, description='affected path')


class ObjectErrorList(BaseModel):
    errors: List[ObjectError]


class ErrorNoACL(BaseModel):
    message: str = Field(..., description='short message explaining the error')
    no_acl: Optional[bool] = Field(
        None, description='true if the group exists but has no ACL'
    )


class User(BaseModel):
    id: str = Field(
        ..., description='A unique identifier for the user. Cannot be edited.'
    )
    creation_date: int = Field(..., description='Unix Epoch in seconds')
    friendly_name: Optional[str] = Field(
        None,
        description='A shorter name for the user than the id. Unlike id it does not identify the user (it\nmight not be unique). Used in some places in the UI.\n',
    )
    email: Optional[str] = Field(
        None,
        description='The email address of the user. If API authentication is enabled, this field is mandatory and will be invited to login.\nIf API authentication is disabled, this field will be ignored. All current APIAuthenticators require the email to be \nlowercase and unique, although custom authenticators may not enforce this.\n',
    )


class CurrentUser(BaseModel):
    user: User


class UserCreation(BaseModel):
    id: str = Field(..., description='a unique identifier for the user.')
    invite_user: Optional[bool] = None


class RBAC(Enum):
    none = 'none'
    simplified = 'simplified'
    internal = 'internal'
    external = 'external'


class LoginUrlMethod(Enum):
    none = 'none'
    redirect = 'redirect'
    select = 'select'


class LoginConfig(BaseModel):
    rbac: Optional[RBAC] = Field(
        None,
        alias='RBAC',
        description='RBAC will remain enabled on GUI if "external".  That only works\nwith an external auth service.\n',
    )
    username_ui_placeholder: Optional[str] = Field(
        None,
        description='Placeholder text to display in the username field of the login form.\n',
    )
    password_ui_placeholder: Optional[str] = Field(
        None,
        description='Placeholder text to display in the password field of the login form.\n',
    )
    login_url: str = Field(..., description='Primary URL to use for login.')
    login_url_method: Optional[LoginUrlMethod] = Field(
        None,
        description='Defines login behavior when login_url is set.\n- none: For OSS users.\n- redirect: Auto-redirect to login_url.\n- select: Show a page to choose between logging in via login_url or with lakeFS credentials.\nIgnored if login_url is not configured.\n',
    )
    login_failed_message: Optional[str] = Field(
        None,
        description='Message to display to users who fail to login; a full sentence that is rendered\nin HTML and may contain a link to a secondary login method\n',
    )
    fallback_login_url: Optional[str] = Field(
        None, description='Secondary URL to offer users to use for login.'
    )
    fallback_login_label: Optional[str] = Field(
        None, description='Label to place on fallback_login_url.'
    )
    login_cookie_names: List[str] = Field(
        ..., description='Cookie names used to store JWT'
    )
    logout_url: str = Field(..., description='URL to use for logging out.')


class State(Enum):
    initialized = 'initialized'
    not_initialized = 'not_initialized'


class SetupState(BaseModel):
    state: Optional[State] = None
    comm_prefs_missing: Optional[bool] = Field(
        None, description='true if the comm prefs are missing.'
    )
    login_config: Optional[LoginConfig] = None


class AccessKeyCredentials(BaseModel):
    access_key_id: constr(min_length=1) = Field(
        ...,
        description='access key ID to set for user for use in integration testing.',
        example='AKIAIOSFODNN7EXAMPLE',
    )
    secret_access_key: constr(min_length=1) = Field(
        ...,
        description='secret access key to set for user for use in integration testing.',
        example='wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY',
    )


class Setup(BaseModel):
    username: str = Field(..., description='an identifier for the user (e.g. jane.doe)')
    key: Optional[AccessKeyCredentials] = None
    firstName: Optional[str] = Field(None, description='the provided first name')
    lastName: Optional[str] = Field(None, description='the provided last name')
    email: Optional[str] = Field(None, description='the provided email')
    companyName: Optional[str] = Field(None, description='the provided company name')
    featureUpdates: Optional[bool] = Field(
        None, description='user preference to receive feature updates'
    )
    securityUpdates: Optional[bool] = Field(
        None, description='user preference to receive security updates'
    )


class CommPrefsInput(BaseModel):
    firstName: Optional[str] = Field(None, description='the provided first name')
    lastName: Optional[str] = Field(None, description='the provided last name')
    email: Optional[str] = Field(None, description='the provided email')
    companyName: Optional[str] = Field(None, description='the provided company name')
    featureUpdates: bool = Field(
        ..., description='user preference to receive feature updates'
    )
    securityUpdates: bool = Field(
        ..., description='user preference to receive security updates'
    )


class Credentials(BaseModel):
    access_key_id: str
    creation_date: int = Field(..., description='Unix Epoch in seconds')


class CredentialsList(BaseModel):
    pagination: Pagination
    results: List[Credentials]


class CredentialsWithSecret(BaseModel):
    access_key_id: str
    secret_access_key: str
    creation_date: int = Field(..., description='Unix Epoch in seconds')


class Group(BaseModel):
    id: str
    name: Optional[str] = None
    description: Optional[str] = None
    creation_date: int = Field(..., description='Unix Epoch in seconds')


class GroupList(BaseModel):
    pagination: Pagination
    results: List[Group]


class AuthCapabilities(BaseModel):
    invite_user: Optional[bool] = None
    forgot_password: Optional[bool] = None


class UserList(BaseModel):
    pagination: Pagination
    results: List[User]


class LoginInformation(BaseModel):
    access_key_id: str
    secret_access_key: str


class ExternalLoginInformation(BaseModel):
    token_expiration_duration: Optional[int] = None
    identityRequest: Dict[str, Any]


class StsAuthRequest(BaseModel):
    code: str
    state: str
    redirect_uri: str
    ttl_seconds: Optional[int] = Field(
        None,
        description='The time-to-live for the generated token in seconds.  The default\nvalue is 3600 seconds (1 hour) maximum time allowed is 12 hours.\n',
    )


class AuthenticationToken(BaseModel):
    token: str = Field(
        ..., description='a JWT token that could be used to authenticate requests'
    )
    token_expiration: Optional[int] = Field(None, description='Unix Epoch in seconds')


class GroupCreation(BaseModel):
    id: str
    description: Optional[str] = None


class PolicyCondition(RootModel[Optional[Dict[str, List[str]]]]):
    pass


class Effect(Enum):
    allow = 'allow'
    deny = 'deny'


class Statement(BaseModel):
    effect: Effect
    resource: str
    action: List[str] = Field(..., min_length=1)
    condition: Optional[Dict[str, PolicyCondition]] = Field(
        None, description='Optional conditions for when this statement applies.'
    )


class Policy(BaseModel):
    id: str
    creation_date: Optional[int] = Field(None, description='Unix Epoch in seconds')
    statement: List[Statement] = Field(..., min_length=1)


class PolicyList(BaseModel):
    pagination: Pagination
    results: List[Policy]


class ACL(BaseModel):
    permission: str = Field(
        ...,
        description='Permission level to give this ACL.  "Read", "Write", "Super" and\n"Admin" are all supported.\n',
    )


class StorageConfig(BaseModel):
    blockstore_type: str
    blockstore_namespace_example: str
    blockstore_namespace_ValidityRegex: str
    default_namespace_prefix: Optional[str] = None
    pre_sign_support: bool
    pre_sign_support_ui: bool
    import_support: bool
    import_validity_regex: str
    pre_sign_multipart_upload: Optional[bool] = None
    blockstore_id: Optional[str] = None
    blockstore_description: Optional[str] = None


class StorageConfigList(RootModel[List[StorageConfig]]):
    pass


class VersionConfig(BaseModel):
    version: Optional[str] = None
    version_context: Optional[str] = None
    latest_version: Optional[str] = None
    upgrade_recommended: Optional[bool] = None
    upgrade_url: Optional[str] = None


class CustomViewer(BaseModel):
    name: str
    url: str
    extensions: Optional[List[str]] = None
    content_types: Optional[List[str]] = None


class CapabilitiesConfig(BaseModel):
    pass


class GarbageCollectionConfig(BaseModel):
    grace_period: Optional[int] = Field(
        None,
        description='Duration in seconds. Objects created in the recent grace_period will not be collected.',
    )


class Status(Enum):
    failed = 'failed'
    completed = 'completed'


class ActionRun(BaseModel):
    run_id: str
    branch: str
    start_time: datetime
    end_time: Optional[datetime] = None
    event_type: str
    status: Status
    commit_id: str


class ActionRunList(BaseModel):
    pagination: Pagination
    results: List[ActionRun]


class Status1(Enum):
    failed = 'failed'
    completed = 'completed'


class HookRun(BaseModel):
    hook_run_id: str
    action: str
    hook_id: str
    start_time: datetime
    end_time: Optional[datetime] = None
    status: Status1


class HookRunList(BaseModel):
    pagination: Pagination
    results: List[HookRun]


class StagingLocation(BaseModel):
    physical_address: Optional[str] = None
    presigned_url: Optional[str] = Field(
        None,
        description='if presign=true is passed in the request, this field will contain a pre-signed URL to use when uploading',
    )
    presigned_url_expiry: Optional[int] = Field(
        None,
        description='If present and nonzero, physical_address is a pre-signed URL and\nwill expire at this Unix Epoch time.  This will be shorter than\nthe pre-signed URL lifetime if an authentication token is about\nto expire.\n\nThis field is *optional*.\n',
    )


class StagingMetadata(BaseModel):
    staging: StagingLocation
    checksum: str = Field(
        ...,
        description='unique identifier of object content on backing store (typically ETag)',
    )
    size_bytes: int
    user_metadata: Optional[Dict[str, str]] = None
    content_type: Optional[str] = Field(None, description='Object media type')
    mtime: Optional[int] = Field(
        None, description='Unix Epoch in seconds.  May be ignored by server.'
    )
    force: Optional[bool] = False


class GarbageCollectionPrepareResponse(BaseModel):
    run_id: str = Field(
        ...,
        description='a unique identifier generated for this GC job',
        example='64eaa103-d726-4a33-bcb8-7c0b4abfe09e',
    )
    gc_commits_location: str = Field(
        ...,
        description='location of the resulting commits csv table (partitioned by run_id)',
        example='s3://my-storage-namespace/_lakefs/retention/commits',
    )
    gc_addresses_location: str = Field(
        ...,
        description='location to use for expired addresses parquet table (partitioned by run_id)',
        example='s3://my-storage-namespace/_lakefs/retention/addresses',
    )
    gc_commits_presigned_url: Optional[str] = Field(
        None, description='a presigned url to download the commits csv'
    )


class PrepareGarbageCollectionCommitsStatus(BaseModel):
    task_id: str = Field(..., description='the id of the task preparing the GC commits')
    completed: bool = Field(
        ...,
        description='true if the task has completed (either successfully or with an error)',
    )
    update_time: datetime = Field(
        ..., description='last time the task status was updated'
    )
    result: Optional[GarbageCollectionPrepareResponse] = None
    error: Optional[Error] = None


class PrepareGCUncommittedRequest(BaseModel):
    continuation_token: Optional[str] = None


class PrepareGCUncommittedResponse(BaseModel):
    run_id: str
    gc_uncommitted_location: str = Field(
        ..., description='location of uncommitted information data'
    )
    continuation_token: Optional[str] = None


class GarbageCollectionRule(BaseModel):
    branch_id: str
    retention_days: int


class GarbageCollectionRules(BaseModel):
    default_retention_days: int
    branches: List[GarbageCollectionRule]


class BranchProtectionRule(BaseModel):
    pattern: constr(min_length=1) = Field(
        ...,
        description='fnmatch pattern for the branch name, supporting * and ? wildcards',
        example='stable_*',
    )


class Type2(Enum):
    common_prefix = 'common_prefix'
    object = 'object'


class ImportLocation(BaseModel):
    type: Type2 = Field(
        ..., description="Path type, can either be 'common_prefix' or 'object'"
    )
    path: str = Field(
        ...,
        description="A source location to a 'common_prefix' or to a single object. Must match the lakeFS installation blockstore type.",
        example='s3://my-bucket/production/collections/',
    )
    destination: str = Field(
        ...,
        description="Destination for the imported objects on the branch. Must be a relative path to the branch.\nIf the type is an 'object', the destination is the exact object name under the branch.\nIf the type is a 'common_prefix', the destination is the prefix under the branch.\n",
        example='collections/',
    )


class ImportCreation(BaseModel):
    paths: List[ImportLocation]
    commit: CommitCreation
    force: Optional[bool] = False


class RangeMetadata(BaseModel):
    id: str = Field(
        ...,
        description='ID of the range.',
        example='480e19972a6fbe98ab8e81ae5efdfd1a29037587e91244e87abd4adefffdb01c',
    )
    min_key: str = Field(
        ...,
        description='First key in the range.',
        example='production/collections/some/file_1.parquet',
    )
    max_key: str = Field(
        ...,
        description='Last key in the range.',
        example='production/collections/some/file_8229.parquet',
    )
    count: int = Field(..., description='Number of records in the range.')
    estimated_size: int = Field(..., description='Estimated size of the range in bytes')


class ImportStatus(BaseModel):
    completed: bool
    update_time: datetime
    ingested_objects: Optional[int] = Field(
        None, description='Number of objects processed so far'
    )
    metarange_id: Optional[str] = None
    commit: Optional[Commit] = None
    error: Optional[Error] = None


class ImportCreationResponse(BaseModel):
    id: str = Field(..., description='The id of the import process')


class TaskCreation(BaseModel):
    id: str = Field(..., description='The id of the new task')


class MetaRangeCreation(BaseModel):
    ranges: List[RangeMetadata] = Field(..., min_length=1)


class MetaRangeCreationResponse(BaseModel):
    id: Optional[str] = Field(None, description='The id of the created metarange')


class UpdateToken(BaseModel):
    staging_token: str


class StatsEvent(BaseModel):
    class_: str = Field(
        ...,
        alias='class',
        description='stats event class (e.g. "s3_gateway", "openapi_request", "experimental-feature", "ui-event")',
    )
    name: str = Field(
        ...,
        description='stats event name (e.g. "put_object", "create_repository", "<experimental-feature-name>")',
    )
    count: int = Field(..., description='number of events of the class and name')


class StatsEventsList(BaseModel):
    events: List[StatsEvent]


class PresignMultipartUpload(BaseModel):
    upload_id: str
    physical_address: str
    presigned_urls: Optional[List[str]] = None


class UploadPart(BaseModel):
    part_number: int
    etag: str


class UploadPartFrom(BaseModel):
    physical_address: str = Field(
        ...,
        description='The physical address (of the entire intended object) returned from\ncreatePresignMultipartUpload.\n',
    )


class CopyPartSource(BaseModel):
    repository: str
    ref: str
    path: str
    range: Optional[constr(pattern=r'^bytes=((\d*-\d*,? ?)+)$')] = Field(
        None, description='Range of bytes to copy'
    )


class UploadPartCopyFrom(UploadPartFrom):
    copy_source: CopyPartSource = Field(..., description='Source of copy')


class UploadTo(BaseModel):
    presigned_url: str


class CompletePresignMultipartUpload(BaseModel):
    physical_address: str
    parts: List[UploadPart] = Field(
        ...,
        description='List of uploaded parts, should be ordered by ascending part number',
    )
    user_metadata: Optional[Dict[str, str]] = None
    content_type: Optional[str] = Field(None, description='Object media type')


class AbortPresignMultipartUpload(BaseModel):
    physical_address: str


class UsageReport(BaseModel):
    year: int
    month: int
    count: int


class InstallationUsageReport(BaseModel):
    installation_id: str
    reports: List[UsageReport]


class ExternalPrincipalSettings(RootModel[Optional[Dict[str, str]]]):
    pass


class Settings(BaseModel):
    pass


class ExternalPrincipalCreation(BaseModel):
    settings: Optional[Union[List[ExternalPrincipalSettings], Settings]] = None


class Settings1(BaseModel):
    pass


class ExternalPrincipal(BaseModel):
    id: str = Field(
        ...,
        description='A unique identifier for the external principal i.e aws:sts::123:assumed-role/role-name',
    )
    user_id: str = Field(
        ..., description='lakeFS user ID to associate with an external principal.\n'
    )
    settings: Optional[Union[List[ExternalPrincipalSettings], Settings1]] = None


class Status2(Enum):
    open = 'open'
    closed = 'closed'
    merged = 'merged'


class PullRequestBasic(BaseModel):
    status: Optional[Status2] = None
    title: Optional[str] = None
    description: Optional[str] = None


class PullRequest(PullRequestBasic):
    id: str
    creation_date: datetime
    author: str
    source_branch: str
    destination_branch: str
    merged_commit_id: Optional[str] = Field(
        None, description='the commit id of merged PRs'
    )
    closed_date: Optional[datetime] = None


class PullRequestsList(BaseModel):
    pagination: Pagination
    results: List[PullRequest]


class PullRequestCreation(BaseModel):
    title: str
    description: Optional[str] = None
    source_branch: str
    destination_branch: str


class PullRequestCreationResponse(BaseModel):
    id: str = Field(..., description='ID of the pull request')


class Type3(Enum):
    two_dot = 'two_dot'
    three_dot = 'three_dot'


class Type4(Enum):
    two_dot = 'two_dot'
    three_dot = 'three_dot'


class RepositoriesRepositoryBranchesBranchObjectsPostRequest(BaseModel):
    content: Optional[bytes] = Field(
        None, description='Only a single file per upload which must be named "content".'
    )


class Type5(Enum):
    range = 'range'
    meta_range = 'meta_range'


class Type6(Enum):
    range = 'range'
    meta_range = 'meta_range'


class RepositoriesRepositoryBranchProtectionDeleteRequest(BaseModel):
    pattern: str


class Status3(Enum):
    open = 'open'
    closed = 'closed'
    all = 'all'


class Status4(Enum):
    open = 'open'
    closed = 'closed'
    all = 'all'


class DiffObjectStat(BaseModel):
    checksum: str
    mtime: int = Field(..., description='Unix Epoch in seconds')
    content_type: str = Field(..., description='Object media type')
    metadata: Optional[ObjectUserMetadata] = None


class ObjectStats(BaseModel):
    path: str
    path_type: PathType
    physical_address: str = Field(
        ...,
        description='The location of the object on the underlying object store.\nFormatted as a native URI with the object store type as scheme ("s3://...", "gs://...", etc.)\nOr, in the case of presign=true, will be an HTTP URL to be consumed via regular HTTP GET\n',
    )
    physical_address_expiry: Optional[int] = Field(
        None,
        description='If present and nonzero, physical_address is a pre-signed URL and\nwill expire at this Unix Epoch time.  This will be shorter than\nthe pre-signed URL lifetime if an authentication token is about\nto expire.\n\nThis field is *optional*.\n',
    )
    checksum: str
    size_bytes: Optional[int] = Field(
        None,
        description='The number of bytes in the object.  lakeFS always populates this\nfield when returning ObjectStats.  This field is optional _for\nthe client_ to supply, for instance on upload.\n',
    )
    mtime: int = Field(..., description='Unix Epoch in seconds')
    metadata: Optional[ObjectUserMetadata] = None
    content_type: Optional[str] = Field(None, description='Object media type')


class ObjectStatsList(BaseModel):
    pagination: Pagination
    results: List[ObjectStats]


class UpdateObjectUserMetadata(BaseModel):
    set: ObjectUserMetadata = Field(..., description='Set this object user metadata')


class ObjectStageCreation(BaseModel):
    physical_address: str
    checksum: str
    size_bytes: int
    mtime: Optional[int] = Field(None, description='Unix Epoch in seconds')
    metadata: Optional[ObjectUserMetadata] = None
    content_type: Optional[str] = Field(None, description='Object media type')
    force: Optional[bool] = False


class Diff(BaseModel):
    type: Type
    path: str
    path_type: PathType1
    size_bytes: Optional[int] = Field(
        None, description='represents the size of the added/changed/deleted entry'
    )
    right: Optional[DiffObjectStat] = Field(
        None, description='ObjectStats of the right side of the diff.'
    )


class DiffList(BaseModel):
    pagination: Pagination
    results: List[Diff]


class RepositoryDumpStatus(BaseModel):
    id: str = Field(..., description='ID of the task')
    done: bool
    update_time: datetime
    error: Optional[str] = None
    refs: Optional[RefsDump] = None


class UIConfig(BaseModel):
    custom_viewers: Optional[List[CustomViewer]] = None


class ExternalPrincipalList(BaseModel):
    pagination: Pagination
    results: List[ExternalPrincipal]


class Config(BaseModel):
    version_config: Optional[VersionConfig] = None
    storage_config: Optional[StorageConfig] = None
    storage_config_list: Optional[StorageConfigList] = None
    ui_config: Optional[UIConfig] = None
    capabilities_config: Optional[CapabilitiesConfig] = None
