"""
lakeFS API models - split by domain.

Import from sub-modules directly, or use this package for backward compatibility.
"""

from .base import Pagination
from .errors import Error, ErrorNoACL, ObjectError, ObjectErrorList
from .repositories import (
    Repository,
    RepositoryCreation,
    RepositoryDumpStatus,
    RepositoryList,
    RepositoryMetadata,
    RepositoryMetadataKeys,
    RepositoryMetadataSet,
    RepositoryRestoreStatus,
)
from .commits import (
    BranchCreation,
    CherryPickCreation,
    Commit,
    CommitCreation,
    CommitList,
    CommitOverrides,
    CommitRecordCreation,
    FindMergeBaseResult,
    Merge,
    MergeResult,
    Ref,
    RefList,
    RefsDump,
    RefsRestore,
    ResetCreation,
    RevertCreation,
    TagCreation,
)
from .objects import (
    AbortPresignMultipartUpload,
    CompletePresignMultipartUpload,
    CopyPartSource,
    ObjectCopyCreation,
    ObjectStageCreation,
    ObjectStats,
    ObjectStatsList,
    ObjectUserMetadata,
    PathList,
    PathType,
    PresignMultipartUpload,
    StagingLocation,
    StagingMetadata,
    StorageURI,
    UnderlyingObjectProperties,
    UpdateObjectUserMetadata,
    UpdateToken,
    UploadPart,
    UploadPartCopyFrom,
    UploadPartFrom,
    UploadTo,
)
from .diffs import (
    ActionRun,
    ActionRunList,
    ActionRunStatus,
    BranchProtectionRule,
    Diff,
    DiffList,
    DiffObjectStat,
    DiffPathType,
    DiffType,
    GarbageCollectionConfig,
    GarbageCollectionPrepareResponse,
    GarbageCollectionRule,
    GarbageCollectionRules,
    HookRun,
    HookRunList,
    ImportCreation,
    ImportCreationResponse,
    ImportLocation,
    ImportLocationType,
    ImportStatus,
    MetaRangeCreation,
    MetaRangeCreationResponse,
    PrepareGarbageCollectionCommitsStatus,
    PrepareGCUncommittedRequest,
    PrepareGCUncommittedResponse,
    RangeMetadata,
    TaskCreation,
    TaskInfo,
)
from .auth import (
    ACL,
    RBAC,
    AccessKeyCredentials,
    AuthCapabilities,
    AuthenticationToken,
    CommPrefsInput,
    Credentials,
    CredentialsList,
    CredentialsWithSecret,
    CurrentUser,
    Effect,
    ExternalLoginInformation,
    ExternalPrincipal,
    ExternalPrincipalCreation,
    ExternalPrincipalList,
    ExternalPrincipalSettings,
    Group,
    GroupCreation,
    GroupList,
    LoginConfig,
    LoginInformation,
    LoginUrlMethod,
    Policy,
    PolicyCondition,
    PolicyList,
    Setup,
    SetupState,
    Settings,
    Settings1,
    State,
    Statement,
    StsAuthRequest,
    User,
    UserCreation,
    UserList,
)
from .pull_requests import (
    PullRequest,
    PullRequestBasic,
    PullRequestCreation,
    PullRequestCreationResponse,
    PullRequestStatus,
    PullRequestsList,
)
from .config import (
    CapabilitiesConfig,
    Config,
    CustomViewer,
    InstallationUsageReport,
    StatsEvent,
    StatsEventsList,
    StorageConfig,
    StorageConfigList,
    UIConfig,
    UsageReport,
    VersionConfig,
)

__all__ = [
    # base
    'Pagination',
    # errors
    'Error', 'ErrorNoACL', 'ObjectError', 'ObjectErrorList',
    # repositories
    'Repository', 'RepositoryCreation', 'RepositoryDumpStatus', 'RepositoryList',
    'RepositoryMetadata', 'RepositoryMetadataKeys', 'RepositoryMetadataSet',
    'RepositoryRestoreStatus',
    # commits
    'BranchCreation', 'CherryPickCreation', 'Commit', 'CommitCreation', 'CommitList',
    'CommitOverrides', 'CommitRecordCreation', 'FindMergeBaseResult', 'Merge',
    'MergeResult', 'Ref', 'RefList', 'RefsDump', 'RefsRestore', 'ResetCreation',
    'RevertCreation', 'TagCreation',
    # objects
    'AbortPresignMultipartUpload', 'CompletePresignMultipartUpload', 'CopyPartSource',
    'ObjectCopyCreation', 'ObjectStageCreation', 'ObjectStats', 'ObjectStatsList',
    'ObjectUserMetadata', 'PathList', 'PathType', 'PresignMultipartUpload',
    'StagingLocation', 'StagingMetadata', 'StorageURI', 'UnderlyingObjectProperties',
    'UpdateObjectUserMetadata', 'UpdateToken', 'UploadPart', 'UploadPartCopyFrom',
    'UploadPartFrom', 'UploadTo',
    # diffs / gc / actions
    'ActionRun', 'ActionRunList', 'ActionRunStatus', 'BranchProtectionRule', 'Diff',
    'DiffList', 'DiffObjectStat', 'DiffPathType', 'DiffType', 'GarbageCollectionConfig',
    'GarbageCollectionPrepareResponse', 'GarbageCollectionRule', 'GarbageCollectionRules',
    'HookRun', 'HookRunList', 'ImportCreation', 'ImportCreationResponse', 'ImportLocation',
    'ImportLocationType', 'ImportStatus', 'MetaRangeCreation', 'MetaRangeCreationResponse',
    'PrepareGarbageCollectionCommitsStatus', 'PrepareGCUncommittedRequest',
    'PrepareGCUncommittedResponse', 'RangeMetadata', 'TaskCreation', 'TaskInfo',
    # auth
    'ACL', 'RBAC', 'AccessKeyCredentials', 'AuthCapabilities', 'AuthenticationToken',
    'CommPrefsInput', 'Credentials', 'CredentialsList', 'CredentialsWithSecret',
    'CurrentUser', 'Effect', 'ExternalLoginInformation', 'ExternalPrincipal',
    'ExternalPrincipalCreation', 'ExternalPrincipalList', 'ExternalPrincipalSettings',
    'Group', 'GroupCreation', 'GroupList', 'LoginConfig', 'LoginInformation',
    'LoginUrlMethod', 'Policy', 'PolicyCondition', 'PolicyList', 'Setup', 'SetupState',
    'Settings', 'Settings1', 'State', 'Statement', 'StsAuthRequest', 'User',
    'UserCreation', 'UserList',
    # pull requests
    'PullRequest', 'PullRequestBasic', 'PullRequestCreation', 'PullRequestCreationResponse',
    'PullRequestStatus', 'PullRequestsList',
    # config / stats
    'CapabilitiesConfig', 'Config', 'CustomViewer', 'InstallationUsageReport', 'StatsEvent',
    'StatsEventsList', 'StorageConfig', 'StorageConfigList', 'UIConfig', 'UsageReport',
    'VersionConfig',
]
